%%%%%%%%%%%%%%%%%%%%   path: classes\@collection   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@collection\addObjects">classes\@collection\addObjects</a>               -  adds the given objects to the collection.
%   <a href="matlab:help classes\@collection\attachToDom">classes\@collection\attachToDom</a>              - % Create empty collection node with the attribute 'shape'
%   <a href="matlab:help classes\@collection\char">classes\@collection\char</a>                     -  convert a collection object into a string.
%   <a href="matlab:help classes\@collection\cohere">classes\@collection\cohere</a>                   -  estimates the coherence between time-series objects in a collection object.
%   <a href="matlab:help classes\@collection\collection">classes\@collection\collection</a>               -  constructor for collection class.
%   <a href="matlab:help classes\@collection\copy">classes\@collection\copy</a>                     -  makes a (deep) copy of the input collection objects.
%   <a href="matlab:help classes\@collection\cpsd">classes\@collection\cpsd</a>                     -  estimates the cross-spectral density between time-series objects in a collection object.
%   <a href="matlab:help classes\@collection\disp">classes\@collection\disp</a>                     -  overloads display functionality for collection objects.
%   <a href="matlab:help classes\@collection\filter">classes\@collection\filter</a>                   -  overrides the filter function for analysis objects in a collection object.
%   <a href="matlab:help classes\@collection\filtfilt">classes\@collection\filtfilt</a>                 -  overrides the filtfilt function for analysis objects in a collection object.
%   <a href="matlab:help classes\@collection\fromDom">classes\@collection\fromDom</a>                  - % Get shape
%   <a href="matlab:help classes\@collection\fromInput">classes\@collection\fromInput</a>                - Construct a collection object from ltpda_uoh objects.
%   <a href="matlab:help classes\@collection\fromRepository">classes\@collection\fromRepository</a>           - Retrieve a ltpda_uo from a repository
%   <a href="matlab:help classes\@collection\fromStruct">classes\@collection\fromStruct</a>               -  creates from a structure a COLLECTION object.
%   <a href="matlab:help classes\@collection\generateConstructorPlist">classes\@collection\generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@collection\getObjectAtIndex">classes\@collection\getObjectAtIndex</a>         -  index into the inner objects of one collection object.
%   <a href="matlab:help classes\@collection\getObjectByName">classes\@collection\getObjectByName</a>          -  returns an inside object selected by the name.
%   <a href="matlab:help classes\@collection\getObjectsOfClass">classes\@collection\getObjectsOfClass</a>        -  returns all objects of the specified class in a collection-object.
%   <a href="matlab:help classes\@collection\identifyInsideObjs">classes\@collection\identifyInsideObjs</a>       -  Static method which identify the inside objects and configuration PLISTs.
%   <a href="matlab:help classes\@collection\iplot">classes\@collection\iplot</a>                    -  calls ao/iplot on all inner ao objects.
%   <a href="matlab:help classes\@collection\lincom">classes\@collection\lincom</a>                   -  make a linear combination of objects within the collection
%   <a href="matlab:help classes\@collection\loadobj">classes\@collection\loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help classes\@collection\nobjs">classes\@collection\nobjs</a>                    -  Returns the number of objects in the inner object array.
%   <a href="matlab:help classes\@collection\objTypes">classes\@collection\objTypes</a>                 -  returns a cell array of the class types for each object in the
%   <a href="matlab:help classes\@collection\plot">classes\@collection\plot</a>                     -  the collection objects.
%   <a href="matlab:help classes\@collection\plotTrends">classes\@collection\plotTrends</a>               -  plots the trend collections produced by ao/trends.
%   <a href="matlab:help classes\@collection\removeObjectAtIndex">classes\@collection\removeObjectAtIndex</a>      -  removes the object at the specified position from the collection.
%   <a href="matlab:help classes\@collection\saveAllObjects">classes\@collection\saveAllObjects</a>           -  index into the inner objects of one collection object.
%   <a href="matlab:help classes\@collection\setNames">classes\@collection\setNames</a>                 -  Sets the property 'names' of a collection object.
%   <a href="matlab:help classes\@collection\setObjectAtIndex">classes\@collection\setObjectAtIndex</a>         -  sets an input object to the collection.
%   <a href="matlab:help classes\@collection\setObjs">classes\@collection\setObjs</a>                  -  sets the 'objs' property of a collection object.
%   <a href="matlab:help classes\@collection\subsasgn">classes\@collection\subsasgn</a>                 -  overloads the setting behaviour for collection objects.
%   <a href="matlab:help classes\@collection\subsref">classes\@collection\subsref</a>                  -  overloads the referencing behaviour for collection objects.
%   <a href="matlab:help classes\@collection\summaryReport">classes\@collection\summaryReport</a>            -  generates an HTML report about the inner objects.
%   <a href="matlab:help classes\@collection\tfe">classes\@collection\tfe</a>                      -  estimates the transfer function between time-series objects in a collection object.
%   <a href="matlab:help classes\@collection\toCell">classes\@collection\toCell</a>                   -  toCells the objects in a collection and sets them to the given output
%   <a href="matlab:help classes\@collection\unpack">classes\@collection\unpack</a>                   -  unpacks the objects in a collection and sets them to the given output
%   <a href="matlab:help classes\@collection\update_struct">classes\@collection\update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@collection\wrapperEval">classes\@collection\wrapperEval</a>              - % loop over inner objects
