%%%%%%%%%%%%%%%%%%%%   path: classes\@matrix   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@matrix\attachToDom">classes\@matrix\attachToDom</a>              - % Create empty matrix node with the attribute 'shape'
%   <a href="matlab:help classes\@matrix\char">classes\@matrix\char</a>                     -  convert a matrix object into a string.
%   <a href="matlab:help classes\@matrix\clearObjHistories">classes\@matrix\clearObjHistories</a>        -  Clear the history of the inside objects.
%   <a href="matlab:help classes\@matrix\cohere">classes\@matrix\cohere</a>                   -  estimates the coherence between elements of the vector.
%   <a href="matlab:help classes\@matrix\copy">classes\@matrix\copy</a>                     -  makes a (deep) copy of the input matrix objects.
%   <a href="matlab:help classes\@matrix\cpsd">classes\@matrix\cpsd</a>                     -  estimates the cross-spectral density between elements of the vector.
%   <a href="matlab:help classes\@matrix\crb">classes\@matrix\crb</a>                      -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help classes\@matrix\cross">classes\@matrix\cross</a>                    -  implements cross operator for matrix objects.
%   <a href="matlab:help classes\@matrix\ctranspose">classes\@matrix\ctranspose</a>               -  implements conjugate transpose operator for matrix objects.
%   <a href="matlab:help classes\@matrix\delay">classes\@matrix\delay</a>                    -  overloads ao/delay for matrix objects.
%   <a href="matlab:help classes\@matrix\det">classes\@matrix\det</a>                      -  evaluates the determinant for matrix object.
%   <a href="matlab:help classes\@matrix\disp">classes\@matrix\disp</a>                     -  overloads display functionality for matrix objects.
%   <a href="matlab:help classes\@matrix\dispersion">classes\@matrix\dispersion</a>               -  computes the dispersion function
%   <a href="matlab:help classes\@matrix\dispersionLoop">classes\@matrix\dispersionLoop</a>           -  computes the dispersion function
%   <a href="matlab:help classes\@matrix\double">classes\@matrix\double</a>                   -  - converts a matrix of objects into matrix of numbers
%   <a href="matlab:help classes\@matrix\elementOp">classes\@matrix\elementOp</a>                -  applies the given operator to the input matrices.
%   <a href="matlab:help classes\@matrix\fftfilt">classes\@matrix\fftfilt</a>                  -  fft filter for matrix objects
%   <a href="matlab:help classes\@matrix\filter">classes\@matrix\filter</a>                   -  implements N-dim filter operator for matrix objects.
%   <a href="matlab:help classes\@matrix\filtfilt">classes\@matrix\filtfilt</a>                 -  overrides the filtfilt function for matrices of analysis objects.
%   <a href="matlab:help classes\@matrix\fisher">classes\@matrix\fisher</a>                   -  Fisher matrix calculation for MATRIX models.
%   <a href="matlab:help classes\@matrix\flscovSegments">classes\@matrix\flscovSegments</a>           -  - Tool to perform a least square fit in frequency domain
%   <a href="matlab:help classes\@matrix\fromDom">classes\@matrix\fromDom</a>                  - % Get shape
%   <a href="matlab:help classes\@matrix\fromInput">classes\@matrix\fromInput</a>                - Construct a matrix object from ltpda_uoh objects.
%   <a href="matlab:help classes\@matrix\fromStruct">classes\@matrix\fromStruct</a>               -  creates from a structure a MATRIX object.
%   <a href="matlab:help classes\@matrix\fromValues">classes\@matrix\fromValues</a>               - Construct a matrix object with multiple AOs built from input values.
%   <a href="matlab:help classes\@matrix\generateConstructorPlist">classes\@matrix\generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@matrix\getObjectAtIndex">classes\@matrix\getObjectAtIndex</a>         -  index into the inner objects of one matrix object.
%   <a href="matlab:help classes\@matrix\inv">classes\@matrix\inv</a>                      -  evaluates the inverse for matrix object.
%   <a href="matlab:help classes\@matrix\iplot">classes\@matrix\iplot</a>                    -  calls ao/iplot on all inner ao objects.
%   <a href="matlab:help classes\@matrix\lcohere">classes\@matrix\lcohere</a>                  -  estimates the coherence between elements of the vector using
%   <a href="matlab:help classes\@matrix\lcpsd">classes\@matrix\lcpsd</a>                    -  estimates the coherence between elements of the vector using a
%   <a href="matlab:help classes\@matrix\lincom">classes\@matrix\lincom</a>                   -  make a linear combination of analysis objects
%   <a href="matlab:help classes\@matrix\linearize">classes\@matrix\linearize</a>                -  output the derivatives of the model relative to the parameters.
%   <a href="matlab:help classes\@matrix\linfitsvd">classes\@matrix\linfitsvd</a>                -  Linear fit with singular value decomposition
%   <a href="matlab:help classes\@matrix\linlsqsvd">classes\@matrix\linlsqsvd</a>                -  Linear least squares with singular value decomposition
%   <a href="matlab:help classes\@matrix\loadobj">classes\@matrix\loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help classes\@matrix\loglikelihood">classes\@matrix\loglikelihood</a>            - LOGLIKELIHOOD: Compute log-likelihood for MATRIX objects
%   <a href="matlab:help classes\@matrix\loglikelihood_core">classes\@matrix\loglikelihood_core</a>       - loglikelihood: Compute log-likelihood for MATRIX objects
%   <a href="matlab:help classes\@matrix\lscov">classes\@matrix\lscov</a>                    -  is a wrapper for MATLAB's lscov function.
%   <a href="matlab:help classes\@matrix\ltfe">classes\@matrix\ltfe</a>                     -  estimates the transfer function between elements of the vector using
%   <a href="matlab:help classes\@matrix\matrix">classes\@matrix\matrix</a>                   -  constructor for matrix class.
%   <a href="matlab:help classes\@matrix\mchNoisegen">classes\@matrix\mchNoisegen</a>              -  Generates multichannel noise data series given a model
%   <a href="matlab:help classes\@matrix\mchNoisegenFilter">classes\@matrix\mchNoisegenFilter</a>        -  Construct a matrix filter from cross-spectral density matrix
%   <a href="matlab:help classes\@matrix\mcmc">classes\@matrix\mcmc</a>                     -  estimates paramters using a Monte Carlo Markov Chain.
%   <a href="matlab:help classes\@matrix\mean">classes\@matrix\mean</a>                     -  evaluates the meanerse for matrix object.
%   <a href="matlab:help classes\@matrix\minus">classes\@matrix\minus</a>                    -  implements subtraction operator for ltpda model objects.
%   <a href="matlab:help classes\@matrix\modelSelect">classes\@matrix\modelSelect</a>              -  - method to compute the Bayes Factor using RJMCMC, LF, LM, SBIC methods
%   <a href="matlab:help classes\@matrix\mtimes">classes\@matrix\mtimes</a>                   -  implements mtimes operator for matrix objects.
%   <a href="matlab:help classes\@matrix\osize">classes\@matrix\osize</a>                    -  Returns the size of the inner object array.
%   <a href="matlab:help classes\@matrix\plot">classes\@matrix\plot</a>                     -  the matrix objects on the given axes.
%   <a href="matlab:help classes\@matrix\plus">classes\@matrix\plus</a>                     -  implements addition operator for matrix objects.
%   <a href="matlab:help classes\@matrix\power">classes\@matrix\power</a>                    - TIMES implements multiplication operator for matrix objects.
%   <a href="matlab:help classes\@matrix\rdivide">classes\@matrix\rdivide</a>                  -  implements division operator for matrix objects.
%   <a href="matlab:help classes\@matrix\rotate">classes\@matrix\rotate</a>                   -  applies rotation factor to matrix objects
%   <a href="matlab:help classes\@matrix\setObjs">classes\@matrix\setObjs</a>                  -  sets the 'objs' property of a matrix object.
%   <a href="matlab:help classes\@matrix\simplify">classes\@matrix\simplify</a>                 -  each model in the matrix.
%   <a href="matlab:help classes\@matrix\spsdSubtraction">classes\@matrix\spsdSubtraction</a>          -  makes a sPSD-weighted least-square iterative fit
%   <a href="matlab:help classes\@matrix\tdfit">classes\@matrix\tdfit</a>                    -  fit a MATRIX of transfer function SMODELs to a matrix of input and output signals.
%   <a href="matlab:help classes\@matrix\tfe">classes\@matrix\tfe</a>                      -  estimates the transfer functions between elements of the vector.
%   <a href="matlab:help classes\@matrix\times">classes\@matrix\times</a>                    -  implements multiplication operator for matrix objects.
%   <a href="matlab:help classes\@matrix\toArray">classes\@matrix\toArray</a>                  -  unpacks the objects in a matrix and places them into a MATLAB
%   <a href="matlab:help classes\@matrix\transpose">classes\@matrix\transpose</a>                -  implements transpose operator for matrix objects.
%   <a href="matlab:help classes\@matrix\unpack">classes\@matrix\unpack</a>                   -  unpacks the objects in a matrix and sets them to the given output
%   <a href="matlab:help classes\@matrix\update_struct">classes\@matrix\update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@matrix\wrapperEval">classes\@matrix\wrapperEval</a>              - % loop over inner objects
%   <a href="matlab:help classes\@matrix\xspec">classes\@matrix\xspec</a>                    - MATRIX/XSPEC applies the given cross-spectral density method to the vecor
