%%%%%%%%%%%%%%%%%%%%   path: classes\@unit   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@unit\HzToS">classes\@unit\HzToS</a>         -  convert any 'Hz' units to 's'
%   <a href="matlab:help classes\@unit\atan2">classes\@unit\atan2</a>         -  implements atan2 operator for two unit objects
%   <a href="matlab:help classes\@unit\attachToDom">classes\@unit\attachToDom</a>   - % Create empty unit node with the attribute 'shape'
%   <a href="matlab:help classes\@unit\char">classes\@unit\char</a>          -  convert a unit object into a string.
%   <a href="matlab:help classes\@unit\copy">classes\@unit\copy</a>          -  makes a (deep) copy of the input unit objects.
%   <a href="matlab:help classes\@unit\disp">classes\@unit\disp</a>          -  display an unit object.
%   <a href="matlab:help classes\@unit\factor">classes\@unit\factor</a>        -  factorises units in to numerator and denominator units.
%   <a href="matlab:help classes\@unit\fromDom">classes\@unit\fromDom</a>       - % There exist two possibilities.
%   <a href="matlab:help classes\@unit\fromStruct">classes\@unit\fromStruct</a>    -  creates from a structure a UNIT object.
%   <a href="matlab:help classes\@unit\isemptyunit">classes\@unit\isemptyunit</a>   -  overloads the isequal operator for ltpda unit objects.
%   <a href="matlab:help classes\@unit\isequal">classes\@unit\isequal</a>       -  overloads the isequal operator for ltpda unit objects.
%   <a href="matlab:help classes\@unit\loadobj">classes\@unit\loadobj</a>       -  is called by the load function for user objects.
%   <a href="matlab:help classes\@unit\mpower">classes\@unit\mpower</a>        -  implements mpower operator for unit objects.
%   <a href="matlab:help classes\@unit\mrdivide">classes\@unit\mrdivide</a>      -  implements mrdivide operator for unit objects.
%   <a href="matlab:help classes\@unit\mtimes">classes\@unit\mtimes</a>        -  implements mtimes operator for unit objects.
%   <a href="matlab:help classes\@unit\plus">classes\@unit\plus</a>          -  implements addition operator for unit objects.
%   <a href="matlab:help classes\@unit\power">classes\@unit\power</a>         -  implements power operator for unit objects.
%   <a href="matlab:help classes\@unit\rdivide">classes\@unit\rdivide</a>       -  implements rdivide operator for unit objects.
%   <a href="matlab:help classes\@unit\sToHz">classes\@unit\sToHz</a>         -  convert any 's' units to 'Hz'
%   <a href="matlab:help classes\@unit\setVals">classes\@unit\setVals</a>       -  set the vals field of the unit
%   <a href="matlab:help classes\@unit\simplify">classes\@unit\simplify</a>      -  the units.
%   <a href="matlab:help classes\@unit\split">classes\@unit\split</a>         -  split a unit into a set of single units.
%   <a href="matlab:help classes\@unit\sqrt">classes\@unit\sqrt</a>          -  computes the square root of an unit object.
%   <a href="matlab:help classes\@unit\string">classes\@unit\string</a>        -  converts a unit object to a command string which will recreate the unit object.
%   <a href="matlab:help classes\@unit\times">classes\@unit\times</a>         -  implements times operator for unit objects.
%   <a href="matlab:help classes\@unit\toSI">classes\@unit\toSI</a>          -  converts the units to SI.
%   <a href="matlab:help classes\@unit\tolabel">classes\@unit\tolabel</a>       -  converts a unit object to LaTeX string suitable for use as axis labels.
%   <a href="matlab:help classes\@unit\unit">classes\@unit\unit</a>          -  a helper class for implementing units in LTPDA.
%   <a href="matlab:help classes\@unit\update_struct">classes\@unit\update_struct</a> -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@unit\xlabel">classes\@unit\xlabel</a>        -  place a xlabel on the given axes taking into account the units and
%   <a href="matlab:help classes\@unit\ylabel">classes\@unit\ylabel</a>        -  place a ylabel on the given axes taking into account the units and
