%%%%%%%%%%%%%%%%%%%%   path: classes\@ao   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@ao\abs">classes\@ao\abs</a>                      -  overloads the Absolute value method for analysis objects.
%   <a href="matlab:help classes\@ao\acos">classes\@ao\acos</a>                     -  overloads the acos method for analysis objects.
%   <a href="matlab:help classes\@ao\all">classes\@ao\all</a>                      -  overloads the all operator for analysis objects. True if all elements 
%   <a href="matlab:help classes\@ao\and">classes\@ao\and</a>                      -  (&) overloads the and (&) method for analysis objects.
%   <a href="matlab:help classes\@ao\angle">classes\@ao\angle</a>                    -  overloads the angle operator for analysis objects.
%   <a href="matlab:help classes\@ao\any">classes\@ao\any</a>                      -  overloads the any operator for analysis objects. True if any element 
%   <a href="matlab:help classes\@ao\ao">classes\@ao\ao</a>                       -  analysis object class constructor.
%   <a href="matlab:help classes\@ao\ao2numMatrices">classes\@ao\ao2numMatrices</a>           -  transforms AO objects to numerical matrices.
%   <a href="matlab:help classes\@ao\applymethod">classes\@ao\applymethod</a>              -  to the analysis object
%   <a href="matlab:help classes\@ao\applyoperator">classes\@ao\applyoperator</a>            -  to the analysis object
%   <a href="matlab:help classes\@ao\asin">classes\@ao\asin</a>                     -  overloads the asin method for analysis objects.
%   <a href="matlab:help classes\@ao\atan">classes\@ao\atan</a>                     -  overloads the atan method for analysis objects.
%   <a href="matlab:help classes\@ao\atan2">classes\@ao\atan2</a>                    -  overloads the atan2 operator for analysis objects. Four quadrant inverse tangent.
%   <a href="matlab:help classes\@ao\attachToDom">classes\@ao\attachToDom</a>              - % Create empty ao node with the attribute 'shape'
%   <a href="matlab:help classes\@ao\average">classes\@ao\average</a>                  -  averages aos point-by-point
%   <a href="matlab:help classes\@ao\bandpass">classes\@ao\bandpass</a>                 -  AOs containing time-series data.
%   <a href="matlab:help classes\@ao\bandreject">classes\@ao\bandreject</a>               -  AOs containing time-series data.
%   <a href="matlab:help classes\@ao\bicohere">classes\@ao\bicohere</a>                 -  computes the bicoherence of two input time-series
%   <a href="matlab:help classes\@ao\bilinfit">classes\@ao\bilinfit</a>                 -  is a linear fitting tool
%   <a href="matlab:help classes\@ao\bin_data">classes\@ao\bin_data</a>                 -  rebins aos data, on logarithmic scale, linear scale, or arbitrarly chosen.
%   <a href="matlab:help classes\@ao\blrms">classes\@ao\blrms</a>                    -  computes band-limited RMS trends of the input time-series.
%   <a href="matlab:help classes\@ao\buildWhitener1D">classes\@ao\buildWhitener1D</a>          -  builds a whitening filter based on the input frequency-series.
%   <a href="matlab:help classes\@ao\cast">classes\@ao\cast</a>                     -  - converts the numeric values in an AO to the data type specified by type.
%   <a href="matlab:help classes\@ao\cat">classes\@ao\cat</a>                      -  concatenate AOs into a row vector.
%   <a href="matlab:help classes\@ao\cdfplot">classes\@ao\cdfplot</a>                  -  makes cumulative distribution plot
%   <a href="matlab:help classes\@ao\cgfill">classes\@ao\cgfill</a>                   -  fills specified gaps in the data given an inital guess for the spectrum.
%   <a href="matlab:help classes\@ao\char">classes\@ao\char</a>                     -  overloads char() function for analysis objects.
%   <a href="matlab:help classes\@ao\checkDataType">classes\@ao\checkDataType</a>            -  Throws an error for AOs with a specified data-type.
%   <a href="matlab:help classes\@ao\checkNumericDataTypes">classes\@ao\checkNumericDataTypes</a>    -  Throws an error for AOs if the numeric data types doesn't match to an AO method.
%   <a href="matlab:help classes\@ao\checkTimestamps">classes\@ao\checkTimestamps</a>          -  performs a check on the timestamps of the input AOs.
%   <a href="matlab:help classes\@ao\clearErrors">classes\@ao\clearErrors</a>              - % Set units
%   <a href="matlab:help classes\@ao\cohere">classes\@ao\cohere</a>                   -  estimates the coherence between time-series objects
%   <a href="matlab:help classes\@ao\complex">classes\@ao\complex</a>                  -  overloads the complex operator for Analysis objects.
%   <a href="matlab:help classes\@ao\compute">classes\@ao\compute</a>                  -  performs the given operations on the input AOs.
%   <a href="matlab:help classes\@ao\computeDFT">classes\@ao\computeDFT</a>               -  Computes DFT using FFT or Goertzel
%   <a href="matlab:help classes\@ao\computeperiodogram">classes\@ao\computeperiodogram</a>       -    Periodogram spectral estimation.
%   <a href="matlab:help classes\@ao\confint">classes\@ao\confint</a>                  -  Calculates confidence levels and variance for psd, lpsd, cohere, lcohere and curvefit parameters
%   <a href="matlab:help classes\@ao\conj">classes\@ao\conj</a>                     -  overloads the conjugate operator for analysis objects.
%   <a href="matlab:help classes\@ao\consolidate">classes\@ao\consolidate</a>              -  resamples all input AOs onto the same time grid.
%   <a href="matlab:help classes\@ao\conv">classes\@ao\conv</a>                     -  vector convolution.
%   <a href="matlab:help classes\@ao\conv_noisegen">classes\@ao\conv_noisegen</a>            -  calls the matlab function conv.m to convolute poles and zeros from a given pzmodel
%   <a href="matlab:help classes\@ao\convert">classes\@ao\convert</a>                  -  perform various conversions on the ao.
%   <a href="matlab:help classes\@ao\copy">classes\@ao\copy</a>                     -  makes a (deep) copy of the input AOs.
%   <a href="matlab:help classes\@ao\corr">classes\@ao\corr</a>                     -  estimate linear correlation coefficients.
%   <a href="matlab:help classes\@ao\cos">classes\@ao\cos</a>                      -  overloads the cos method for analysis objects.
%   <a href="matlab:help classes\@ao\cov">classes\@ao\cov</a>                      -  estimate covariance of data streams.
%   <a href="matlab:help classes\@ao\cpsd">classes\@ao\cpsd</a>                     -  estimates the cross-spectral density between time-series objects
%   <a href="matlab:help classes\@ao\crb">classes\@ao\crb</a>                      -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help classes\@ao\crbound">classes\@ao\crbound</a>                  -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help classes\@ao\csvGenerateData">classes\@ao\csvGenerateData</a>          -  Default method to convert a analysis object into csv data.
%   <a href="matlab:help classes\@ao\ctranspose">classes\@ao\ctranspose</a>               -  overloads the ' operator for Analysis Objects.
%   <a href="matlab:help classes\@ao\cumsum">classes\@ao\cumsum</a>                   -  overloads the cumsum operator for analysis objects.
%   <a href="matlab:help classes\@ao\delay">classes\@ao\delay</a>                    -  delays a time-series using various methods.
%   <a href="matlab:help classes\@ao\delayEstimate">classes\@ao\delayEstimate</a>            -  estimates the delay between two AOs
%   <a href="matlab:help classes\@ao\delay_fractional_core">classes\@ao\delay_fractional_core</a>    -  core method to implement fractional delay
%   <a href="matlab:help classes\@ao\demux">classes\@ao\demux</a>                    -  splits the input vector of AOs into a number of output AOs.
%   <a href="matlab:help classes\@ao\det">classes\@ao\det</a>                      -  overloads the determinant function for analysis objects.
%   <a href="matlab:help classes\@ao\detectOutliers">classes\@ao\detectOutliers</a>           -  locates outliers in data.
%   <a href="matlab:help classes\@ao\detrend">classes\@ao\detrend</a>                  -  detrends the input analysis object using a polynomial of degree N.
%   <a href="matlab:help classes\@ao\dft">classes\@ao\dft</a>                      -  computes the DFT of the input time-series at the requested frequencies.
%   <a href="matlab:help classes\@ao\diag">classes\@ao\diag</a>                     -  overloads the diagonal operator for analysis objects.
%   <a href="matlab:help classes\@ao\diff">classes\@ao\diff</a>                     -  differentiates the data in AO.
%   <a href="matlab:help classes\@ao\diff2p_core">classes\@ao\diff2p_core</a>              - (No help available)
%   <a href="matlab:help classes\@ao\diff3p_core">classes\@ao\diff3p_core</a>              - (No help available)
%   <a href="matlab:help classes\@ao\diff5p_core">classes\@ao\diff5p_core</a>              - (No help available)
%   <a href="matlab:help classes\@ao\disp">classes\@ao\disp</a>                     -  implement terminal display for analysis object.
%   <a href="matlab:help classes\@ao\dispersionLoop">classes\@ao\dispersionLoop</a>           - dipersionLoop computes the dispersion function in loop
%   <a href="matlab:help classes\@ao\double">classes\@ao\double</a>                   -  overloads double() function for analysis objects.
%   <a href="matlab:help classes\@ao\downsample">classes\@ao\downsample</a>               -  decimate AOs by an integer factor.
%   <a href="matlab:help classes\@ao\dropduplicates">classes\@ao\dropduplicates</a>           -  drops all duplicate samples in time-series AOs.
%   <a href="matlab:help classes\@ao\dsmean">classes\@ao\dsmean</a>                   -  performs a simple downsampling by taking the mean of every N samples.
%   <a href="matlab:help classes\@ao\dtfe">classes\@ao\dtfe</a>                     -  estimates transfer function between time-series objects.
%   <a href="matlab:help classes\@ao\dx">classes\@ao\dx</a>                       -  Get the data property 'dx'.
%   <a href="matlab:help classes\@ao\dy">classes\@ao\dy</a>                       -  Get the data property 'dy'.
%   <a href="matlab:help classes\@ao\dz">classes\@ao\dz</a>                       - DX Get the data property 'dz'.
%   <a href="matlab:help classes\@ao\ecdf">classes\@ao\ecdf</a>                     -  calculate empirical cumulative distribution function
%   <a href="matlab:help classes\@ao\edgedetect">classes\@ao\edgedetect</a>               -  detects edges in a binary pulse-train.
%   <a href="matlab:help classes\@ao\eig">classes\@ao\eig</a>                      -  overloads the eigenvalues/eigenvectors function for analysis objects.
%   <a href="matlab:help classes\@ao\elementOp">classes\@ao\elementOp</a>                -  applies the given operator to the data.
%   <a href="matlab:help classes\@ao\eq">classes\@ao\eq</a>                       -  overloads == operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\eqmotion">classes\@ao\eqmotion</a>                 -  solves numerically a given linear equation of motion
%   <a href="matlab:help classes\@ao\evaluateModel">classes\@ao\evaluateModel</a>            -  evaluate a curvefit model.
%   <a href="matlab:help classes\@ao\exp">classes\@ao\exp</a>                      -  overloads the exp operator for analysis objects. Exponential.
%   <a href="matlab:help classes\@ao\export">classes\@ao\export</a>                   -  export the data of an analysis object to a text file.
%   <a href="matlab:help classes\@ao\fft">classes\@ao\fft</a>                      -  overloads the fft method for Analysis objects.
%   <a href="matlab:help classes\@ao\fft_1sided_core">classes\@ao\fft_1sided_core</a>          - (No help available)
%   <a href="matlab:help classes\@ao\fft_2sided_core">classes\@ao\fft_2sided_core</a>          - (No help available)
%   <a href="matlab:help classes\@ao\fft_core">classes\@ao\fft_core</a>                 -  Simple core method which computes the fft.
%   <a href="matlab:help classes\@ao\fftfilt">classes\@ao\fftfilt</a>                  -  overrides the fft filter function for analysis objects.
%   <a href="matlab:help classes\@ao\fftfilt_core">classes\@ao\fftfilt_core</a>             -  Simple core method which computes the fft filter.
%   <a href="matlab:help classes\@ao\filtSubtract">classes\@ao\filtSubtract</a>             -  subtracts a frequency dependent noise contribution from an input ao.
%   <a href="matlab:help classes\@ao\filter">classes\@ao\filter</a>                   -  overrides the filter function for analysis objects.
%   <a href="matlab:help classes\@ao\filtfilt">classes\@ao\filtfilt</a>                 -  overrides the filtfilt function for analysis objects.
%   <a href="matlab:help classes\@ao\find">classes\@ao\find</a>                     -  particular samples that satisfy the input query and return a new AO.
%   <a href="matlab:help classes\@ao\findFsMax">classes\@ao\findFsMax</a>                -  Returns the max Fs of a set of AOs
%   <a href="matlab:help classes\@ao\findFsMin">classes\@ao\findFsMin</a>                -  Returns the min Fs of a set of AOs
%   <a href="matlab:help classes\@ao\findShortestVector">classes\@ao\findShortestVector</a>       -  Returns the length of the shortest vector in samples
%   <a href="matlab:help classes\@ao\firwhiten">classes\@ao\firwhiten</a>                -  whitens the input time-series by building an FIR whitening filter.
%   <a href="matlab:help classes\@ao\fixAxisData">classes\@ao\fixAxisData</a>              -  up the data type according to the users chosen axis
%   <a href="matlab:help classes\@ao\fixfs">classes\@ao\fixfs</a>                    -  resamples the input time-series to have a fixed sample rate.
%   <a href="matlab:help classes\@ao\flscov">classes\@ao\flscov</a>                   -  - Tool to perform a least square fit in frequency domain.
%   <a href="matlab:help classes\@ao\flscov_global">classes\@ao\flscov_global</a>            -  - Tool to perform a least square fit in frequency domain
%   <a href="matlab:help classes\@ao\fngen">classes\@ao\fngen</a>                    -  creates an arbitrarily long time-series based on the input PSD.
%   <a href="matlab:help classes\@ao\fq2fac">classes\@ao\fq2fac</a>                   -  is a private function and is called by ngconv.m which can be found in the
%   <a href="matlab:help classes\@ao\fromComplexDatafile">classes\@ao\fromComplexDatafile</a>      -  Construct an AO from filename AND parameter list
%   <a href="matlab:help classes\@ao\fromDataInMAT">classes\@ao\fromDataInMAT</a>            -  Convert a saved data-array into an AO with a tsdata-object
%   <a href="matlab:help classes\@ao\fromDatafile">classes\@ao\fromDatafile</a>             -  Construct an ao from filename AND parameter list
%   <a href="matlab:help classes\@ao\fromDom">classes\@ao\fromDom</a>                  - % Get shape
%   <a href="matlab:help classes\@ao\fromFSfcn">classes\@ao\fromFSfcn</a>                -  Construct an ao from a fs-function string
%   <a href="matlab:help classes\@ao\fromFcn">classes\@ao\fromFcn</a>                  -  Construct an ao from a function string
%   <a href="matlab:help classes\@ao\fromParameter">classes\@ao\fromParameter</a>            -  Construct an ao from a param object
%   <a href="matlab:help classes\@ao\fromPest">classes\@ao\fromPest</a>                 -  Construct a AO from a pest.
%   <a href="matlab:help classes\@ao\fromPolyval">classes\@ao\fromPolyval</a>              -  Construct an ao from polynomial coefficients
%   <a href="matlab:help classes\@ao\fromProcinfo">classes\@ao\fromProcinfo</a>             -  returns for a given key-name the value of the procinfo-plist
%   <a href="matlab:help classes\@ao\fromPzmodel">classes\@ao\fromPzmodel</a>              -  Construct a time-series ao from polynomial coefficients
%   <a href="matlab:help classes\@ao\fromSModel">classes\@ao\fromSModel</a>               -  Construct a AO from an smodel.
%   <a href="matlab:help classes\@ao\fromSpecWin">classes\@ao\fromSpecWin</a>              -  Construct an ao from a Spectral window
%   <a href="matlab:help classes\@ao\fromStruct">classes\@ao\fromStruct</a>               -  creates from a structure an analysis object.
%   <a href="matlab:help classes\@ao\fromTSfcn">classes\@ao\fromTSfcn</a>                -  Construct an ao from a ts-function string
%   <a href="matlab:help classes\@ao\fromVals">classes\@ao\fromVals</a>                 -  Construct an ao from a value set
%   <a href="matlab:help classes\@ao\fromWaveform">classes\@ao\fromWaveform</a>             -  Construct an ao from a waveform
%   <a href="matlab:help classes\@ao\fromXYFcn">classes\@ao\fromXYFcn</a>                -  Construct an ao from a function f(x) string
%   <a href="matlab:help classes\@ao\fromXYVals">classes\@ao\fromXYVals</a>               -  Construct an ao from a value set
%   <a href="matlab:help classes\@ao\fromXYZVals">classes\@ao\fromXYZVals</a>              -  Construct an ao from a value set
%   <a href="matlab:help classes\@ao\fs">classes\@ao\fs</a>                       -  Get the data property 'fs'.
%   <a href="matlab:help classes\@ao\gapfilling">classes\@ao\gapfilling</a>               -  fills possible gaps in data.
%   <a href="matlab:help classes\@ao\gapfillingoptim">classes\@ao\gapfillingoptim</a>          -  fills possible gaps in data.
%   <a href="matlab:help classes\@ao\ge">classes\@ao\ge</a>                       -  overloads >= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\generateConstructorPlist">classes\@ao\generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@ao\getAbsTimeRange">classes\@ao\getAbsTimeRange</a>          -  returns a timespan object which span the absolute time range of an AO
%   <a href="matlab:help classes\@ao\getCommonInterval">classes\@ao\getCommonInterval</a>        -  Estimates the common interval spun by a group of Analysis Objects
%   <a href="matlab:help classes\@ao\getGeneralInterval">classes\@ao\getGeneralInterval</a>       -  Estimates the maximum interval spun by a group of Analysis Objects
%   <a href="matlab:help classes\@ao\getKSCValPSD">classes\@ao\getKSCValPSD</a>             -  provides critical value for KStest on the PSD
%   <a href="matlab:help classes\@ao\getdof">classes\@ao\getdof</a>                   -  Calculates degrees of freedom for psd, lpsd, cohere and lcohere
%   <a href="matlab:help classes\@ao\gnuplot">classes\@ao\gnuplot</a>                  -  a gnuplot interface for AOs.
%   <a href="matlab:help classes\@ao\gt">classes\@ao\gt</a>                       -  overloads > operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\heterodyne">classes\@ao\heterodyne</a>               -  heterodynes time-series.
%   <a href="matlab:help classes\@ao\highpass">classes\@ao\highpass</a>                 -  highpass AOs containing time-series data.
%   <a href="matlab:help classes\@ao\hist">classes\@ao\hist</a>                     -  overloads the histogram function (hist) of MATLAB for Analysis Objects.
%   <a href="matlab:help classes\@ao\hypot">classes\@ao\hypot</a>                    -  overloads robust computation of the square root of the sum of squares for AOs.
%   <a href="matlab:help classes\@ao\iacf">classes\@ao\iacf</a>                     -  computes the inverse auto-correlation function from a spectrum.
%   <a href="matlab:help classes\@ao\ifft">classes\@ao\ifft</a>                     -  overloads the ifft operator for Analysis objects.
%   <a href="matlab:help classes\@ao\ifft_1sided_even_core">classes\@ao\ifft_1sided_even_core</a>    - (No help available)
%   <a href="matlab:help classes\@ao\ifft_1sided_odd_core">classes\@ao\ifft_1sided_odd_core</a>     - (No help available)
%   <a href="matlab:help classes\@ao\ifft_2sided_core">classes\@ao\ifft_2sided_core</a>         - (No help available)
%   <a href="matlab:help classes\@ao\ifft_core">classes\@ao\ifft_core</a>                -  Simple core method which computes the ifft.
%   <a href="matlab:help classes\@ao\ifft_plain_core">classes\@ao\ifft_plain_core</a>          - (No help available)
%   <a href="matlab:help classes\@ao\imag">classes\@ao\imag</a>                     -  overloads the imaginary operator for analysis objects.
%   <a href="matlab:help classes\@ao\integrate">classes\@ao\integrate</a>                -  integrates the data in AO.
%   <a href="matlab:help classes\@ao\interp">classes\@ao\interp</a>                   -  interpolate the values in the input AO(s) at new values.
%   <a href="matlab:help classes\@ao\interpmissing">classes\@ao\interpmissing</a>            -  interpolate missing samples in a time-series.
%   <a href="matlab:help classes\@ao\intersect">classes\@ao\intersect</a>                -  overloads the intersect operator for Analysis objects.
%   <a href="matlab:help classes\@ao\inv">classes\@ao\inv</a>                      -  overloads the inverse function for analysis objects.
%   <a href="matlab:help classes\@ao\iplot">classes\@ao\iplot</a>                    -  provides an intelligent plotting tool for LTPDA.
%   <a href="matlab:help classes\@ao\iplotyy">classes\@ao\iplotyy</a>                  -  provides an intelligent plotting tool for LTPDA.
%   <a href="matlab:help classes\@ao\join">classes\@ao\join</a>                     -  multiple AOs into a single AO.
%   <a href="matlab:help classes\@ao\kstest">classes\@ao\kstest</a>                   -  perform KS test on input AOs
%   <a href="matlab:help classes\@ao\lcohere">classes\@ao\lcohere</a>                  -  implement magnitude-squadred coherence estimation on a log frequency axis.
%   <a href="matlab:help classes\@ao\lcpsd">classes\@ao\lcpsd</a>                    -  implement cross-power-spectral density estimation on a log frequency axis.
%   <a href="matlab:help classes\@ao\le">classes\@ao\le</a>                       -  overloads <= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\len">classes\@ao\len</a>                      -  overloads the length operator for Analysis objects. Length of the data samples.
%   <a href="matlab:help classes\@ao\linSubtract">classes\@ao\linSubtract</a>              -  subtracts a linear contribution from an input ao.
%   <a href="matlab:help classes\@ao\lincom">classes\@ao\lincom</a>                   -  make a linear combination of analysis objects
%   <a href="matlab:help classes\@ao\linedetect">classes\@ao\linedetect</a>               -  find spectral lines in the ao/fsdata objects.
%   <a href="matlab:help classes\@ao\linfit">classes\@ao\linfit</a>                   -  is a linear fitting tool
%   <a href="matlab:help classes\@ao\linlsqsvd">classes\@ao\linlsqsvd</a>                -  Linear least squares with singular value decomposition
%   <a href="matlab:help classes\@ao\lisovfit">classes\@ao\lisovfit</a>                 -  uses LISO to fit a pole/zero model to the input frequency-series.
%   <a href="matlab:help classes\@ao\ln">classes\@ao\ln</a>                       -  overloads the log operator for analysis objects. Natural logarithm.
%   <a href="matlab:help classes\@ao\loadobj">classes\@ao\loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help classes\@ao\log">classes\@ao\log</a>                      -  overloads the log operator for analysis objects. Natural logarithm.
%   <a href="matlab:help classes\@ao\log10">classes\@ao\log10</a>                    -  overloads the log10 operator for analysis objects. Common (base 10) logarithm.
%   <a href="matlab:help classes\@ao\logical">classes\@ao\logical</a>                  -  overloads logical() function for analysis objects.
%   <a href="matlab:help classes\@ao\lowpass">classes\@ao\lowpass</a>                  -  lowpass AOs containing time-series data.
%   <a href="matlab:help classes\@ao\lpsd">classes\@ao\lpsd</a>                     -  implements the LPSD algorithm for analysis objects.
%   <a href="matlab:help classes\@ao\lscov">classes\@ao\lscov</a>                    -  is a wrapper for MATLAB's lscov function.
%   <a href="matlab:help classes\@ao\lsf">classes\@ao\lsf</a>                      - --------------------------------------------------------------------------
%   <a href="matlab:help classes\@ao\lsf_global">classes\@ao\lsf_global</a>               - --------------------------------------------------------------------------
%   <a href="matlab:help classes\@ao\lt">classes\@ao\lt</a>                       -  overloads < operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\ltf_plan">classes\@ao\ltf_plan</a>                 -  computes all input values needed for the LPSD and LTFE algorithms.
%   <a href="matlab:help classes\@ao\ltfe">classes\@ao\ltfe</a>                     -  implements transfer function estimation computed on a log frequency axis.
%   <a href="matlab:help classes\@ao\lxspec">classes\@ao\lxspec</a>                   -  performs log-scale cross-spectral analysis of various forms.
%   <a href="matlab:help classes\@ao\map3D">classes\@ao\map3D</a>                    -  maps the input 1 or 2D AOs on to a 3D AO
%   <a href="matlab:help classes\@ao\max">classes\@ao\max</a>                      -  computes the maximum value of the data in the AO
%   <a href="matlab:help classes\@ao\mchol">classes\@ao\mchol</a>                    - (No help available)
%   <a href="matlab:help classes\@ao\mcmc">classes\@ao\mcmc</a>                     -  estimates paramters using a Monte Carlo Markov Chain.
%   <a href="matlab:help classes\@ao\md5">classes\@ao\md5</a>                      -  computes an MD5 checksum from an analysis objects.
%   <a href="matlab:help classes\@ao\mean">classes\@ao\mean</a>                     -  computes the mean value of the data in the AO.
%   <a href="matlab:help classes\@ao\median">classes\@ao\median</a>                   -  computes the median value of the data in the AO.
%   <a href="matlab:help classes\@ao\melementOp">classes\@ao\melementOp</a>               -  applies the given matrix operator to the data.
%   <a href="matlab:help classes\@ao\min">classes\@ao\min</a>                      -  computes the minimum value of the data in the AO
%   <a href="matlab:help classes\@ao\minus">classes\@ao\minus</a>                    -  implements subtraction operator for analysis objects.
%   <a href="matlab:help classes\@ao\mlpsd_m">classes\@ao\mlpsd_m</a>                  -  m-file only version of the LPSD algorithm
%   <a href="matlab:help classes\@ao\mlpsd_mex">classes\@ao\mlpsd_mex</a>                -  calls the ltpda_dft.mex to compute the DFT part of the LPSD algorithm
%   <a href="matlab:help classes\@ao\mltfe">classes\@ao\mltfe</a>                    -  compute log-frequency space TF
%   <a href="matlab:help classes\@ao\mod">classes\@ao\mod</a>                      -  overloads the modulus function for analysis objects.
%   <a href="matlab:help classes\@ao\mode">classes\@ao\mode</a>                     -  computes the modal value of the data in the AO.
%   <a href="matlab:help classes\@ao\modelSelect">classes\@ao\modelSelect</a>              -  method to compute the Bayes Factor using RJMCMC, LF, LM, BIC methods
%   <a href="matlab:help classes\@ao\mpower">classes\@ao\mpower</a>                   -  implements mpower operator for analysis objects.
%   <a href="matlab:help classes\@ao\mrdivide">classes\@ao\mrdivide</a>                 -  implements mrdivide operator for analysis objects.
%   <a href="matlab:help classes\@ao\mtimes">classes\@ao\mtimes</a>                   -  implements mtimes operator for analysis objects.
%   <a href="matlab:help classes\@ao\mve">classes\@ao\mve</a>                      - MVE: Minimum Volume Ellipsoid estimator
%   <a href="matlab:help classes\@ao\ne">classes\@ao\ne</a>                       -  overloads ~= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help classes\@ao\ngconv">classes\@ao\ngconv</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help classes\@ao\nginit">classes\@ao\nginit</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help classes\@ao\ngprop">classes\@ao\ngprop</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help classes\@ao\ngsetup">classes\@ao\ngsetup</a>                  -  is called by the function fromPzmodel
%   <a href="matlab:help classes\@ao\ngsetup_vpa">classes\@ao\ngsetup_vpa</a>              - % ALGONAME = mfilename;
%   <a href="matlab:help classes\@ao\noisePower">classes\@ao\noisePower</a>               -  computes the noise power spectral density in a time-series as a function of time.
%   <a href="matlab:help classes\@ao\noisegen1D">classes\@ao\noisegen1D</a>               -  generates colored noise from white noise.
%   <a href="matlab:help classes\@ao\noisegen2D">classes\@ao\noisegen2D</a>               -  generates cross correleted colored noise from white noise.
%   <a href="matlab:help classes\@ao\norm">classes\@ao\norm</a>                     -  overloads the norm operator for analysis objects.
%   <a href="matlab:help classes\@ao\normdist">classes\@ao\normdist</a>                 -  computes the equivalent normal distribution for the data.
%   <a href="matlab:help classes\@ao\not">classes\@ao\not</a>                      -  overloads the logical not operator for analysis objects.
%   <a href="matlab:help classes\@ao\nsecs">classes\@ao\nsecs</a>                    -  Get the data property 'nsecs'.
%   <a href="matlab:help classes\@ao\nyquistplot">classes\@ao\nyquistplot</a>              -  fits a piecewise powerlaw to the given data.
%   <a href="matlab:help classes\@ao\offset">classes\@ao\offset</a>                   -  adds an offset to the data in the AO.
%   <a href="matlab:help classes\@ao\or">classes\@ao\or</a>                       -  (|) overloads the or (|) method for Analysis objects.
%   <a href="matlab:help classes\@ao\overlap">classes\@ao\overlap</a>                  -  This method cuts out the the overlapping data of the input AOs.
%   <a href="matlab:help classes\@ao\pad">classes\@ao\pad</a>                      -  pads the input data series to a given value.
%   <a href="matlab:help classes\@ao\performFFTcore">classes\@ao\performFFTcore</a>           -  performs fft for flscov and flscovSegments
%   <a href="matlab:help classes\@ao\phase">classes\@ao\phase</a>                    -  is the phase operator for analysis objects.
%   <a href="matlab:help classes\@ao\play">classes\@ao\play</a>                     -  plays a time-series using MATLAB's audioplay function.
%   <a href="matlab:help classes\@ao\plot">classes\@ao\plot</a>                     -  the analysis objects on the given axes.
%   <a href="matlab:help classes\@ao\plus">classes\@ao\plus</a>                     -  implements addition operator for analysis objects.
%   <a href="matlab:help classes\@ao\polyfit">classes\@ao\polyfit</a>                  -  overloads polyfit() function of MATLAB for Analysis Objects.
%   <a href="matlab:help classes\@ao\polyfitSpectrum">classes\@ao\polyfitSpectrum</a>          -  does a polynomial fit to the log of the input spectrum.
%   <a href="matlab:help classes\@ao\polynomfit">classes\@ao\polynomfit</a>               -  is a polynomial fitting tool
%   <a href="matlab:help classes\@ao\power">classes\@ao\power</a>                    -  implements power operator for analysis objects.
%   <a href="matlab:help classes\@ao\powerFit">classes\@ao\powerFit</a>                 -  fits a piecewise powerlaw to the given data.
%   <a href="matlab:help classes\@ao\ppsd">classes\@ao\ppsd</a>                     -  makes power spectral density estimates of the time-series objects in the input analysis objects by estimating ARMA models coefficients.
%   <a href="matlab:help classes\@ao\preprocessDataForMCMC">classes\@ao\preprocessDataForMCMC</a>    -  Split, resample and apply FFT to time series for MCMC analysis.
%   <a href="matlab:help classes\@ao\processSetterValues">classes\@ao\processSetterValues</a>      - (No help available)
%   <a href="matlab:help classes\@ao\psd">classes\@ao\psd</a>                      -  makes power spectral density estimates of the time-series objects
%   <a href="matlab:help classes\@ao\psdconf">classes\@ao\psdconf</a>                  -  Calculates confidence levels and variance for psd
%   <a href="matlab:help classes\@ao\psdvfit">classes\@ao\psdvfit</a>                  -  performs a fitting loop to identify model for a psd.
%   <a href="matlab:help classes\@ao\qqplot">classes\@ao\qqplot</a>                   -  makes quantile-quantile plot
%   <a href="matlab:help classes\@ao\quasiSweptSine">classes\@ao\quasiSweptSine</a>           -  computes a transfer function from swept-sine measurements
%   <a href="matlab:help classes\@ao\rdivide">classes\@ao\rdivide</a>                  -  implements division operator for analysis objects.
%   <a href="matlab:help classes\@ao\real">classes\@ao\real</a>                     -  overloads the real operator for analysis objects.
%   <a href="matlab:help classes\@ao\removeVal">classes\@ao\removeVal</a>                -  removes values from the input AO(s).
%   <a href="matlab:help classes\@ao\resample">classes\@ao\resample</a>                 -  overloads resample function for AOs.
%   <a href="matlab:help classes\@ao\resampleToCommonGrid">classes\@ao\resampleToCommonGrid</a>     -  Resamples Analysis Objects to a common grid
%   <a href="matlab:help classes\@ao\rjsample">classes\@ao\rjsample</a>                 -  Reverse Jump MCMC sampling using the "Metropolized Carlin And Chib" Method.
%   <a href="matlab:help classes\@ao\rms">classes\@ao\rms</a>                      -  Calculate RMS deviation from spectrum
%   <a href="matlab:help classes\@ao\rotate">classes\@ao\rotate</a>                   -  applies rotation factor to AOs
%   <a href="matlab:help classes\@ao\round">classes\@ao\round</a>                    -  overloads the Round method for analysis objects.
%   <a href="matlab:help classes\@ao\sDomainFit">classes\@ao\sDomainFit</a>               -  performs a fitting loop to identify model order and
%   <a href="matlab:help classes\@ao\scale">classes\@ao\scale</a>                    -  scales the data in the AO by the specified factor.
%   <a href="matlab:help classes\@ao\scatter3D">classes\@ao\scatter3D</a>                -  Creates from the y-values of the input AOs a new AO with a xyz-data object
%   <a href="matlab:help classes\@ao\scatterData">classes\@ao\scatterData</a>              -  Creates from the y-values of two input AOs an new AO(xydata)
%   <a href="matlab:help classes\@ao\select">classes\@ao\select</a>                   -  select particular samples from the input AOs and return new AOs with only those samples.
%   <a href="matlab:help classes\@ao\setData">classes\@ao\setData</a>                  -  sets the 'data' property of the ao.
%   <a href="matlab:help classes\@ao\setDx">classes\@ao\setDx</a>                    -  sets the 'dx' property of the ao.
%   <a href="matlab:help classes\@ao\setDy">classes\@ao\setDy</a>                    -  sets the 'dy' property of the ao.
%   <a href="matlab:help classes\@ao\setDz">classes\@ao\setDz</a>                    -  sets the 'dz' property of the ao.
%   <a href="matlab:help classes\@ao\setEnbw">classes\@ao\setEnbw</a>                  -  sets the 'enbw' property of the ao/fsdata.
%   <a href="matlab:help classes\@ao\setFs">classes\@ao\setFs</a>                    -  sets the 'fs' property of the ao.
%   <a href="matlab:help classes\@ao\setNavs">classes\@ao\setNavs</a>                  -  sets the 'navs' property of the ao/fsdata.
%   <a href="matlab:help classes\@ao\setReferenceTime">classes\@ao\setReferenceTime</a>         -  sets the t0 to the new value but doesn't move the data in time
%   <a href="matlab:help classes\@ao\setT0">classes\@ao\setT0</a>                    -  sets the 't0' property of the ao.
%   <a href="matlab:help classes\@ao\setToffset">classes\@ao\setToffset</a>               -  sets the 'toffset' property of the ao with tsdata
%   <a href="matlab:help classes\@ao\setUnitsForAxis">classes\@ao\setUnitsForAxis</a>          - % Set units
%   <a href="matlab:help classes\@ao\setX">classes\@ao\setX</a>                     -  sets the 'x' property of the ao.
%   <a href="matlab:help classes\@ao\setXY">classes\@ao\setXY</a>                    -  sets the 'x' and 'y' properties of the ao.
%   <a href="matlab:help classes\@ao\setXaxisName">classes\@ao\setXaxisName</a>             -  sets the x-axis name of the ao.
%   <a href="matlab:help classes\@ao\setXunits">classes\@ao\setXunits</a>                -  sets the 'xunits' property of the ao.
%   <a href="matlab:help classes\@ao\setY">classes\@ao\setY</a>                     -  sets the 'y' property of the ao.
%   <a href="matlab:help classes\@ao\setYaxisName">classes\@ao\setYaxisName</a>             -  sets the y-axis name of the ao.
%   <a href="matlab:help classes\@ao\setYunits">classes\@ao\setYunits</a>                -  sets the 'yunits' property of the ao.
%   <a href="matlab:help classes\@ao\setZ">classes\@ao\setZ</a>                     -  sets the 'z' property of the ao.
%   <a href="matlab:help classes\@ao\setZaxisName">classes\@ao\setZaxisName</a>             -  sets the z-axis name of the ao.
%   <a href="matlab:help classes\@ao\setZunits">classes\@ao\setZunits</a>                -  sets the 'zunits' property of the ao.
%   <a href="matlab:help classes\@ao\sign">classes\@ao\sign</a>                     -  overloads the sign operator for analysis objects.
%   <a href="matlab:help classes\@ao\simplex">classes\@ao\simplex</a>                  -  Multidimensional unconstrained nonlinear minimization (Nelder-Mead)
%   <a href="matlab:help classes\@ao\simplifyXunits">classes\@ao\simplifyXunits</a>           -  simplify the 'xunits' of the ao.
%   <a href="matlab:help classes\@ao\simplifyYunits">classes\@ao\simplifyYunits</a>           -  simplify the 'yunits' property of the ao.
%   <a href="matlab:help classes\@ao\simplifyZunits">classes\@ao\simplifyZunits</a>           -  simplify the 'zunits' of the ao.
%   <a href="matlab:help classes\@ao\sin">classes\@ao\sin</a>                      -  overloads the sin method for analysis objects.
%   <a href="matlab:help classes\@ao\sineParams">classes\@ao\sineParams</a>               -  estimates parameters of sinusoids
%   <a href="matlab:help classes\@ao\smoother">classes\@ao\smoother</a>                 -  smooths a given series of data points using the specified method.
%   <a href="matlab:help classes\@ao\sort">classes\@ao\sort</a>                     -  the values in the AO.
%   <a href="matlab:help classes\@ao\spcorr">classes\@ao\spcorr</a>                   -  calculate Spearman Rank-Order Correlation Coefficient
%   <a href="matlab:help classes\@ao\spectrogram">classes\@ao\spectrogram</a>              -  computes a spectrogram of the given ao/tsdata.
%   <a href="matlab:help classes\@ao\spikecleaning">classes\@ao\spikecleaning</a>            -  detects and corrects possible spikes in analysis objects
%   <a href="matlab:help classes\@ao\split">classes\@ao\split</a>                    -  split an analysis object into the specified segments.
%   <a href="matlab:help classes\@ao\split_samples_core">classes\@ao\split_samples_core</a>       - (No help available)
%   <a href="matlab:help classes\@ao\spsd">classes\@ao\spsd</a>                     -  implements the smoothed (binned) PSD algorithm for analysis objects.
%   <a href="matlab:help classes\@ao\spsdSubtraction">classes\@ao\spsdSubtraction</a>          -  makes a sPSD-weighted least-square iterative fit
%   <a href="matlab:help classes\@ao\sqrt">classes\@ao\sqrt</a>                     -  computes the square root of the data in the AO.
%   <a href="matlab:help classes\@ao\stack">classes\@ao\stack</a>                    -  xydata.
%   <a href="matlab:help classes\@ao\std">classes\@ao\std</a>                      -  computes the standard deviation of the data in the AO.
%   <a href="matlab:help classes\@ao\subsData">classes\@ao\subsData</a>                 -  performs actions on ao objects.
%   <a href="matlab:help classes\@ao\sum">classes\@ao\sum</a>                      -  computes the sum of the data in the AO.
%   <a href="matlab:help classes\@ao\sumjoin">classes\@ao\sumjoin</a>                  -  sums time-series signals togther
%   <a href="matlab:help classes\@ao\summaryReport">classes\@ao\summaryReport</a>            -  generates an HTML report about the input objects.
%   <a href="matlab:help classes\@ao\svd">classes\@ao\svd</a>                      -  overloads the svd (singular value decomposition) function for analysis objects.
%   <a href="matlab:help classes\@ao\svd_fit">classes\@ao\svd_fit</a>                  -  estimates parameters for a linear model using SVD
%   <a href="matlab:help classes\@ao\t0">classes\@ao\t0</a>                       -  Get the data property 't0'.
%   <a href="matlab:help classes\@ao\table">classes\@ao\table</a>                    -  display the data from the AO in a table.
%   <a href="matlab:help classes\@ao\tan">classes\@ao\tan</a>                      -  overloads the tan method for analysis objects.
%   <a href="matlab:help classes\@ao\tdfit">classes\@ao\tdfit</a>                    -  fit a set of smodels to a set of input and output signals..
%   <a href="matlab:help classes\@ao\tfe">classes\@ao\tfe</a>                      -  estimates transfer function between time-series objects.
%   <a href="matlab:help classes\@ao\timeaverage">classes\@ao\timeaverage</a>              -  Averages time series intervals
%   <a href="matlab:help classes\@ao\times">classes\@ao\times</a>                    -  implements multiplication operator for analysis objects.
%   <a href="matlab:help classes\@ao\timeshift">classes\@ao\timeshift</a>                -  for AO/tsdata objects, shifts data in time by the specified value in seconds.
%   <a href="matlab:help classes\@ao\toSI">classes\@ao\toSI</a>                     -  converts the units of the x, y and z axes into SI units.
%   <a href="matlab:help classes\@ao\toffset">classes\@ao\toffset</a>                  -  Get the data property 'toffset'.
%   <a href="matlab:help classes\@ao\transpose">classes\@ao\transpose</a>                -  overloads the .' operator for Analysis Objects.
%   <a href="matlab:help classes\@ao\trends">classes\@ao\trends</a>                   -  computes the trend statistics of the input time-series.
%   <a href="matlab:help classes\@ao\truncate">classes\@ao\truncate</a>                 -  Splits Analysis Objects over a common timespan
%   <a href="matlab:help classes\@ao\uminus">classes\@ao\uminus</a>                   -  overloads the uminus operator for analysis objects.
%   <a href="matlab:help classes\@ao\union">classes\@ao\union</a>                    -  overloads the union operator for Analysis Objects.
%   <a href="matlab:help classes\@ao\unwrap">classes\@ao\unwrap</a>                   -  overloads the unwrap operator for analysis objects.
%   <a href="matlab:help classes\@ao\update_struct">classes\@ao\update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@ao\upsample">classes\@ao\upsample</a>                 -  overloads upsample function for AOs.
%   <a href="matlab:help classes\@ao\validate">classes\@ao\validate</a>                 -  checks that the input Analysis Object is reproducible and valid.
%   <a href="matlab:help classes\@ao\validateSpectrumMod">classes\@ao\validateSpectrumMod</a>      -  statistically validate a model for a psd.
%   <a href="matlab:help classes\@ao\var">classes\@ao\var</a>                      -  computes the variance of the data in the AO.
%   <a href="matlab:help classes\@ao\whiten1D">classes\@ao\whiten1D</a>                 -  whitens the input time-series.
%   <a href="matlab:help classes\@ao\whiten2D">classes\@ao\whiten2D</a>                 -  whiten the noise for two cross correlated time series.
%   <a href="matlab:help classes\@ao\window">classes\@ao\window</a>                   -  applies the specified window to the input time-series objects
%   <a href="matlab:help classes\@ao\wosa">classes\@ao\wosa</a>                     -  implements Welch's overlaped segmented averaging algorithm with
%   <a href="matlab:help classes\@ao\x">classes\@ao\x</a>                        -  Get the data property 'x'.
%   <a href="matlab:help classes\@ao\xaxisname">classes\@ao\xaxisname</a>                -  Get the x axis name of the underlying data object.
%   <a href="matlab:help classes\@ao\xcorr">classes\@ao\xcorr</a>                    -  makes cross-correlation estimates of the time-series
%   <a href="matlab:help classes\@ao\xfit">classes\@ao\xfit</a>                     -  fit a function of x to data.
%   <a href="matlab:help classes\@ao\xor">classes\@ao\xor</a>                      -  overloads the xor (exclusive or) method for Analysis objects.
%   <a href="matlab:help classes\@ao\xspec">classes\@ao\xspec</a>                    -  performs cross-spectral analysis of various forms.
%   <a href="matlab:help classes\@ao\xunits">classes\@ao\xunits</a>                   -  Get the data property 'xunits'.
%   <a href="matlab:help classes\@ao\y">classes\@ao\y</a>                        -  Get the data property 'y'.
%   <a href="matlab:help classes\@ao\yaxisname">classes\@ao\yaxisname</a>                -  Get the y axis name of the underlying data object.
%   <a href="matlab:help classes\@ao\yunits">classes\@ao\yunits</a>                   -  Get the data property 'yunits'.
%   <a href="matlab:help classes\@ao\z">classes\@ao\z</a>                        -  Get the data property 'z'.
%   <a href="matlab:help classes\@ao\zDomainFit">classes\@ao\zDomainFit</a>               -  performs a fitting loop to identify model order and
%   <a href="matlab:help classes\@ao\zaxisname">classes\@ao\zaxisname</a>                -  Get the z axis name of the underlying data object.
%   <a href="matlab:help classes\@ao\zeropad">classes\@ao\zeropad</a>                  -  zero pads the input data series.
%   <a href="matlab:help classes\@ao\zeropad_post_core">classes\@ao\zeropad_post_core</a>        - (No help available)
%   <a href="matlab:help classes\@ao\zunits">classes\@ao\zunits</a>                   -  Get the data property 'zunits'.
