%%%%%%%%%%%%%%%%%%%%   path: classes\@ssm   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@ssm\addParameters">classes\@ssm\addParameters</a>                 -  Adds the parameters to the model.
%   <a href="matlab:help classes\@ssm\append">classes\@ssm\append</a>                        - appends embedded subsytems, with exogenous inputs
%   <a href="matlab:help classes\@ssm\assemble">classes\@ssm\assemble</a>                      - assembles embedded subsytems, with exogenous inputs
%   <a href="matlab:help classes\@ssm\attachToDom">classes\@ssm\attachToDom</a>                   - % Create empty ssm node with the attribute 'shape'
%   <a href="matlab:help classes\@ssm\blockMatAdd">classes\@ssm\blockMatAdd</a>                   - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help classes\@ssm\blockMatFillDiag">classes\@ssm\blockMatFillDiag</a>              - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help classes\@ssm\blockMatFusion">classes\@ssm\blockMatFusion</a>                - fusions a block defined matrix stored inside cell array into one matrix
%   <a href="matlab:help classes\@ssm\blockMatIndex">classes\@ssm\blockMatIndex</a>                 - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help classes\@ssm\blockMatMult">classes\@ssm\blockMatMult</a>                  - multiplies block defined matrix stored inside cell array
%   <a href="matlab:help classes\@ssm\blockMatPrune">classes\@ssm\blockMatPrune</a>                 -  selects lines and columns of a block defined matrices stored in a cell array
%   <a href="matlab:help classes\@ssm\blockMatRecut">classes\@ssm\blockMatRecut</a>                 - cuts a matrix into blocks stored inside cell array
%   <a href="matlab:help classes\@ssm\bode">classes\@ssm\bode</a>                          -  makes a bode plot from the given inputs to outputs.
%   <a href="matlab:help classes\@ssm\bodecst">classes\@ssm\bodecst</a>                       -  makes a bodecst plot from the given inputs to outputs.
%   <a href="matlab:help classes\@ssm\buildParamPlist">classes\@ssm\buildParamPlist</a>               -  builds paramerter plists for the ssm params field.
%   <a href="matlab:help classes\@ssm\c2d">classes\@ssm\c2d</a>                           -  performs actions on ao objects.
%   <a href="matlab:help classes\@ssm\char">classes\@ssm\char</a>                          -  convert a ssm object into a string.
%   <a href="matlab:help classes\@ssm\copy">classes\@ssm\copy</a>                          -  makes a (deep) copy of the input ssm objects.
%   <a href="matlab:help classes\@ssm\cpsd">classes\@ssm\cpsd</a>                          -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help classes\@ssm\cpsdForCorrelatedInputs">classes\@ssm\cpsdForCorrelatedInputs</a>       -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help classes\@ssm\cpsdForIndependentInputs">classes\@ssm\cpsdForIndependentInputs</a>      -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help classes\@ssm\d2c">classes\@ssm\d2c</a>                           -  performs actions on ao objects.
%   <a href="matlab:help classes\@ssm\d2d">classes\@ssm\d2d</a>                           -  performs actions on ao objects.
%   <a href="matlab:help classes\@ssm\diffStepFish">classes\@ssm\diffStepFish</a>                  -  Search for a differantiation step
%   <a href="matlab:help classes\@ssm\disp">classes\@ssm\disp</a>                          -  display ssm object.
%   <a href="matlab:help classes\@ssm\displayProperties">classes\@ssm\displayProperties</a>             - DISPAYPROPERTIES displays the ssm model porperties.
%   <a href="matlab:help classes\@ssm\doBode">classes\@ssm\doBode</a>                        -  makes a bode computation from the given inputs to outputs.
%   <a href="matlab:help classes\@ssm\doSetParameters">classes\@ssm\doSetParameters</a>               -  Sets the values of the given parameters.
%   <a href="matlab:help classes\@ssm\doSimplify">classes\@ssm\doSimplify</a>                    -  enables to do model simplification. It is a private function
%   <a href="matlab:help classes\@ssm\doSimulate">classes\@ssm\doSimulate</a>                    -  simulates a discrete ssm with given inputs
%   <a href="matlab:help classes\@ssm\doSubsParameters">classes\@ssm\doSubsParameters</a>              -  enables to substitute symbollic patameters
%   <a href="matlab:help classes\@ssm\dotview">classes\@ssm\dotview</a>                       -   view an ssm object via the DOT interpreter.
%   <a href="matlab:help classes\@ssm\double">classes\@ssm\double</a>                        - Convert a statespace model object to double arrays for given i/o
%   <a href="matlab:help classes\@ssm\duplicateInput">classes\@ssm\duplicateInput</a>                -  copies the specified input blocks.
%   <a href="matlab:help classes\@ssm\findParameters">classes\@ssm\findParameters</a>                -  returns parameter names matching the given pattern.
%   <a href="matlab:help classes\@ssm\fisher">classes\@ssm\fisher</a>                        -  Fisher matrix calculation for SSMs.
%   <a href="matlab:help classes\@ssm\fromDom">classes\@ssm\fromDom</a>                       - % Get shape
%   <a href="matlab:help classes\@ssm\fromStruct">classes\@ssm\fromStruct</a>                    -  creates from a structure an SSM object.
%   <a href="matlab:help classes\@ssm\generateConstructorPlist">classes\@ssm\generateConstructorPlist</a>      -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@ssm\getParameters">classes\@ssm\getParameters</a>                 -  returns parameter values for the given names.
%   <a href="matlab:help classes\@ssm\getParams">classes\@ssm\getParams</a>                     -  returns the parameter list for this SSM model.
%   <a href="matlab:help classes\@ssm\getPortNamesForBlocks">classes\@ssm\getPortNamesForBlocks</a>         -  returns a list of port names for the given block.
%   <a href="matlab:help classes\@ssm\isStable">classes\@ssm\isStable</a>                      -  tells if ssm is numerically stable
%   <a href="matlab:help classes\@ssm\kalman">classes\@ssm\kalman</a>                        -  applies Kalman filtering to a discrete ssm with given i/o
%   <a href="matlab:help classes\@ssm\loadobj">classes\@ssm\loadobj</a>                       -  is called by the load function for user objects.
%   <a href="matlab:help classes\@ssm\loglikelihood">classes\@ssm\loglikelihood</a>                 - LOGLIKELIHOOD: Compute log-likelihood for SSM objects
%   <a href="matlab:help classes\@ssm\loglikelihood_core">classes\@ssm\loglikelihood_core</a>            - LOGLIKELIHOOD: Compute log-likelihood for SSM objects
%   <a href="matlab:help classes\@ssm\modelHelper_checkParameters">classes\@ssm\modelHelper_checkParameters</a>   -  compare the user requested parameter names to
%   <a href="matlab:help classes\@ssm\modelHelper_declareParameters">classes\@ssm\modelHelper_declareParameters</a> -  builds parameters plists for the ssm params field.
%   <a href="matlab:help classes\@ssm\modelHelper_processInputPlist">classes\@ssm\modelHelper_processInputPlist</a> -  processes the input parameters plists for
%   <a href="matlab:help classes\@ssm\modifyTimeStep">classes\@ssm\modifyTimeStep</a>                -  modifies the timestep of a ssm object
%   <a href="matlab:help classes\@ssm\optimiseForFitting">classes\@ssm\optimiseForFitting</a>            -  reduces the system matrices to doubles and strings.
%   <a href="matlab:help classes\@ssm\parameterDiff">classes\@ssm\parameterDiff</a>                 -  Makes a ssm that produces the output and state derivatives.
%   <a href="matlab:help classes\@ssm\projectNoise">classes\@ssm\projectNoise</a>                  -  performs actions on ao objects.
%   <a href="matlab:help classes\@ssm\psd">classes\@ssm\psd</a>                           -  computes the output theoretical PSD shape with given inputs.
%   <a href="matlab:help classes\@ssm\removeEmptyBlocks">classes\@ssm\removeEmptyBlocks</a>             -  enables to do model simplification
%   <a href="matlab:help classes\@ssm\reorganize">classes\@ssm\reorganize</a>                    - REOGANIZE rearranges a ssm object for fast input to BODE, SIMULATE, PSD.
%   <a href="matlab:help classes\@ssm\reshuffle">classes\@ssm\reshuffle</a>                     -  rearragnes a ssm object using the given inputs and outputs.
%   <a href="matlab:help classes\@ssm\reshuffleSym">classes\@ssm\reshuffleSym</a>                  -  rearragnes a ssm object using the given inputs and outputs.
%   <a href="matlab:help classes\@ssm\resp">classes\@ssm\resp</a>                          -  gives the timewise impulse response of a statespace model.
%   <a href="matlab:help classes\@ssm\respcst">classes\@ssm\respcst</a>                       -  gives the timewise impulse response of a statespace model.
%   <a href="matlab:help classes\@ssm\sMinReal">classes\@ssm\sMinReal</a>                      -  gives a minimal realization of a ssm object by deleting unreached states
%   <a href="matlab:help classes\@ssm\setA">classes\@ssm\setA</a>                          -  sets the A matrices to be the given cell array.
%   <a href="matlab:help classes\@ssm\setB">classes\@ssm\setB</a>                          -  sets the B matrices to be the given cell array.
%   <a href="matlab:help classes\@ssm\setBlockProperties">classes\@ssm\setBlockProperties</a>            -  Sets the specified properties of the specified SSM blocks.
%   <a href="matlab:help classes\@ssm\setC">classes\@ssm\setC</a>                          -  sets the C matrices to be the given cell array.
%   <a href="matlab:help classes\@ssm\setD">classes\@ssm\setD</a>                          -  sets the D matrices to be the given cell array.
%   <a href="matlab:help classes\@ssm\setParameters">classes\@ssm\setParameters</a>                 -  Sets the values of the given parameters.
%   <a href="matlab:help classes\@ssm\setParams">classes\@ssm\setParams</a>                     -  Sets the parameters of the model to the given plist.
%   <a href="matlab:help classes\@ssm\setPortProperties">classes\@ssm\setPortProperties</a>             -  Sets names of the specified SSM ports.
%   <a href="matlab:help classes\@ssm\settlingTime">classes\@ssm\settlingTime</a>                  -  retunrns 1% the settling time of the system.
%   <a href="matlab:help classes\@ssm\simplify">classes\@ssm\simplify</a>                      -  enables to do model simplification
%   <a href="matlab:help classes\@ssm\simulate">classes\@ssm\simulate</a>                      -  simulates a discrete ssm with given inputs
%   <a href="matlab:help classes\@ssm\ssm">classes\@ssm\ssm</a>                           -  statespace model class constructor.
%   <a href="matlab:help classes\@ssm\ssm2dot">classes\@ssm\ssm2dot</a>                       -  converts a statespace model object a DOT file.
%   <a href="matlab:help classes\@ssm\ssm2miir">classes\@ssm\ssm2miir</a>                      -  converts a statespace model object to a miir object
%   <a href="matlab:help classes\@ssm\ssm2pzmodel">classes\@ssm\ssm2pzmodel</a>                   -  converts a time-continuous statespace model object to a pzmodel
%   <a href="matlab:help classes\@ssm\ssm2rational">classes\@ssm\ssm2rational</a>                  -  converts a statespace model object to a rational frac. object
%   <a href="matlab:help classes\@ssm\ssm2ss">classes\@ssm\ssm2ss</a>                        -  converts a statespace model object to a MATLAB statespace object.
%   <a href="matlab:help classes\@ssm\ssmFromDescription">classes\@ssm\ssmFromDescription</a>            - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\ssmFromMiir">classes\@ssm\ssmFromMiir</a>                   - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\ssmFromParfrac">classes\@ssm\ssmFromParfrac</a>                - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\ssmFromPzmodel">classes\@ssm\ssmFromPzmodel</a>                - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\ssmFromRational">classes\@ssm\ssmFromRational</a>               - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\ssmFromss">classes\@ssm\ssmFromss</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes\@ssm\steadyState">classes\@ssm\steadyState</a>                   -  returns a possible value for the steady state of an ssm.
%   <a href="matlab:help classes\@ssm\subsParameters">classes\@ssm\subsParameters</a>                -  enables to substitute symbolic patameters
%   <a href="matlab:help classes\@ssm\update_struct">classes\@ssm\update_struct</a>                 -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@ssm\validate">classes\@ssm\validate</a>                      -  Completes and checks the content a ssm object
%   <a href="matlab:help classes\@ssm\viewDetails">classes\@ssm\viewDetails</a>                   -  performs actions on ssm objects.
