%%%%%%%%%%%%%%%%%%%%   path: classes\@mfh   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@mfh\attachToDom">classes\@mfh\attachToDom</a>                    - % create empty mfir node with the attribute 'shape'
%   <a href="matlab:help classes\@mfh\char">classes\@mfh\char</a>                           -  convert a mfh object into a string.
%   <a href="matlab:help classes\@mfh\copy">classes\@mfh\copy</a>                           -  makes a (deep) copy of the input mfh objects.
%   <a href="matlab:help classes\@mfh\declare_objects">classes\@mfh\declare_objects</a>                -  declares all constants and sub-functions in the workspace
%   <a href="matlab:help classes\@mfh\disp">classes\@mfh\disp</a>                           -  overloads display functionality for mfh objects.
%   <a href="matlab:help classes\@mfh\elementOp">classes\@mfh\elementOp</a>                      -  applies the given operator to the models.
%   <a href="matlab:help classes\@mfh\eval">classes\@mfh\eval</a>                           - % Check inputs
%   <a href="matlab:help classes\@mfh\fisher">classes\@mfh\fisher</a>                         -  Calculation of the Fisher Information Matrix/Covariance
%   <a href="matlab:help classes\@mfh\flscov">classes\@mfh\flscov</a>                         -  - Tool to perform a least square fit in frequency domain.
%   <a href="matlab:help classes\@mfh\fminsearch">classes\@mfh\fminsearch</a>                     -  uses a simplex search to minimise the given function handle.
%   <a href="matlab:help classes\@mfh\fminsearchbnd">classes\@mfh\fminsearchbnd</a>                  -  uses a simplex search to minimise the given function handle
%   <a href="matlab:help classes\@mfh\fromDom">classes\@mfh\fromDom</a>                        - % Get shape
%   <a href="matlab:help classes\@mfh\fromStruct">classes\@mfh\fromStruct</a>                     -  creates from a structure a COLLECTION object.
%   <a href="matlab:help classes\@mfh\function_handle">classes\@mfh\function_handle</a>                -  returns a MATLAB function handle version of the function.
%   <a href="matlab:help classes\@mfh\generateConstructorPlist">classes\@mfh\generateConstructorPlist</a>       -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@mfh\getFitErrors">classes\@mfh\getFitErrors</a>                   -  calculates fisher matrix approximation of fit parameters
%   <a href="matlab:help classes\@mfh\getHessian">classes\@mfh\getHessian</a>                     -  calculate Hessian matrix for a given function.
%   <a href="matlab:help classes\@mfh\getJacobian">classes\@mfh\getJacobian</a>                    -  calculate Jacobian matrix for a given function.
%   <a href="matlab:help classes\@mfh\lincom">classes\@mfh\lincom</a>                         -  make a linear combination of supplied models objects
%   <a href="matlab:help classes\@mfh\loadobj">classes\@mfh\loadobj</a>                        -  is called by the load function for user objects.
%   <a href="matlab:help classes\@mfh\loglikelihood">classes\@mfh\loglikelihood</a>                  - LOGLIKELIHOOD: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_ao_td">classes\@mfh\loglikelihood_ao_td</a>            - loglikelihood_core_td: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core">classes\@mfh\loglikelihood_core</a>             - loglikelihood_core: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core_log">classes\@mfh\loglikelihood_core_log</a>         - loglikelihood_core_log: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core_noiseFit_v1">classes\@mfh\loglikelihood_core_noiseFit_v1</a> - loglikelihood_core_noiseFit_v1: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core_student">classes\@mfh\loglikelihood_core_student</a>     - loglikelihood_core_student: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core_td">classes\@mfh\loglikelihood_core_td</a>          - loglikelihood_core_td: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_core_whittle">classes\@mfh\loglikelihood_core_whittle</a>     - loglikelihood_core_whittle: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\loglikelihood_hyper">classes\@mfh\loglikelihood_hyper</a>            - loglikelihood_core: Compute log-likelihood for MFH objects
%   <a href="matlab:help classes\@mfh\mfh">classes\@mfh\mfh</a>                            -  function handle class constructor.
%   <a href="matlab:help classes\@mfh\minus">classes\@mfh\minus</a>                          -  implements subtraction operator for mfh objects.
%   <a href="matlab:help classes\@mfh\multinest">classes\@mfh\multinest</a>                      - (No help available)
%   <a href="matlab:help classes\@mfh\num2cell">classes\@mfh\num2cell</a>                       -  Convert numeric array into cell array.
%   <a href="matlab:help classes\@mfh\paramCovMat">classes\@mfh\paramCovMat</a>                    -  calculate the covariace matrix for the parameters.
%   <a href="matlab:help classes\@mfh\plus">classes\@mfh\plus</a>                           -  implements addition operator for mfh objects.
%   <a href="matlab:help classes\@mfh\rdivide">classes\@mfh\rdivide</a>                        -  implements division operator for mfh objects.
%   <a href="matlab:help classes\@mfh\setConstObjects">classes\@mfh\setConstObjects</a>                -  sets the 'constObjects' property of a mfh object.
%   <a href="matlab:help classes\@mfh\setInputObjects">classes\@mfh\setInputObjects</a>                -  sets the 'inputObjects' property of a mfh object.
%   <a href="matlab:help classes\@mfh\setNumeric">classes\@mfh\setNumeric</a>                     -  sets the 'numeric' property of a mfh object.
%   <a href="matlab:help classes\@mfh\setParamsToConst">classes\@mfh\setParamsToConst</a>               -  set the given parameters to be constant in the model.
%   <a href="matlab:help classes\@mfh\setSubfuncs">classes\@mfh\setSubfuncs</a>                    -  sets the 'subfuncs' property of a mfh object.
%   <a href="matlab:help classes\@mfh\subsref">classes\@mfh\subsref</a>                        - % if we didn't return already, call the built-in MATLAB subsref
%   <a href="matlab:help classes\@mfh\testHessianMatrix">classes\@mfh\testHessianMatrix</a>              -  Performs a random study of the n-dimensional error ellipsoide for a given confidence level.
%   <a href="matlab:help classes\@mfh\times">classes\@mfh\times</a>                          -  implements multiplication operator for mfh objects.
%   <a href="matlab:help classes\@mfh\update_struct">classes\@mfh\update_struct</a>                  -  update the input structure to the current ltpda version
