%%%%%%%%%%%%%%%%%%%%   path: classes\@pest   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@pest\attachToDom">classes\@pest\attachToDom</a>              - % Create empty pest node with the attribute 'shape'
%   <a href="matlab:help classes\@pest\char">classes\@pest\char</a>                     -  convert a pest object into a string.
%   <a href="matlab:help classes\@pest\combine">classes\@pest\combine</a>                  -  combines multiple pest objects.
%   <a href="matlab:help classes\@pest\combineExps">classes\@pest\combineExps</a>              -  combine the results of different parameter estimation
%   <a href="matlab:help classes\@pest\computePdf">classes\@pest\computePdf</a>               - computes Probability Density Function from a pest object
%   <a href="matlab:help classes\@pest\copy">classes\@pest\copy</a>                     -  makes a (deep) copy of the input pest objects.
%   <a href="matlab:help classes\@pest\disp">classes\@pest\disp</a>                     -  overloads display functionality for pest objects.
%   <a href="matlab:help classes\@pest\double">classes\@pest\double</a>                   -  overloads double() function for pest objects.
%   <a href="matlab:help classes\@pest\eval">classes\@pest\eval</a>                     -  evaluate a pest object
%   <a href="matlab:help classes\@pest\find">classes\@pest\find</a>                     -  Creates analysis objects from the selected parameter(s).
%   <a href="matlab:help classes\@pest\fromAOs">classes\@pest\fromAOs</a>                  -  construct a pest object from different values.
%   <a href="matlab:help classes\@pest\fromDom">classes\@pest\fromDom</a>                  - % Get shape
%   <a href="matlab:help classes\@pest\fromStruct">classes\@pest\fromStruct</a>               -  creates from a structure a PEST object.
%   <a href="matlab:help classes\@pest\fromValues">classes\@pest\fromValues</a>               -  construct a pest object from different values.
%   <a href="matlab:help classes\@pest\generateConstructorPlist">classes\@pest\generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@pest\genericSet">classes\@pest\genericSet</a>               -  sets values to a pest property.
%   <a href="matlab:help classes\@pest\getY">classes\@pest\getY</a>                     -  Get the data property 'y'.
%   <a href="matlab:help classes\@pest\jtable">classes\@pest\jtable</a>                   -  display the parameters from PEST objects in a java table.
%   <a href="matlab:help classes\@pest\loadobj">classes\@pest\loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help classes\@pest\mcmcPlot">classes\@pest\mcmcPlot</a>                 -  - Tool to visualise results of a MCMC sampling.
%   <a href="matlab:help classes\@pest\mve">classes\@pest\mve</a>                      - MVE: Minimum Volume Ellipsoid estimator
%   <a href="matlab:help classes\@pest\pest">classes\@pest\pest</a>                     -  constructor for parameter estimates (pest) class.
%   <a href="matlab:help classes\@pest\plot">classes\@pest\plot</a>                     -  the pest objects on the given axes.
%   <a href="matlab:help classes\@pest\removeParameters">classes\@pest\removeParameters</a>         -  removes the named parameters from the pests.
%   <a href="matlab:help classes\@pest\setChain">classes\@pest\setChain</a>                 - SETCHI2 Set the property 'chain'
%   <a href="matlab:help classes\@pest\setChi2">classes\@pest\setChi2</a>                  -  Set the property 'chi2'
%   <a href="matlab:help classes\@pest\setCorr">classes\@pest\setCorr</a>                  -  Set the property 'corr'
%   <a href="matlab:help classes\@pest\setCov">classes\@pest\setCov</a>                   -  Set the property 'cov'
%   <a href="matlab:help classes\@pest\setDof">classes\@pest\setDof</a>                   -  Set the property 'dof'
%   <a href="matlab:help classes\@pest\setDy">classes\@pest\setDy</a>                    -  Set the property 'dy'
%   <a href="matlab:help classes\@pest\setDyForParameter">classes\@pest\setDyForParameter</a>        -  Sets the according dy-error for the specified parameter.
%   <a href="matlab:help classes\@pest\setModels">classes\@pest\setModels</a>                -  Set the property 'models'
%   <a href="matlab:help classes\@pest\setNames">classes\@pest\setNames</a>                 -  Set the property 'names'
%   <a href="matlab:help classes\@pest\setPdf">classes\@pest\setPdf</a>                   -  Set the property 'pdf'
%   <a href="matlab:help classes\@pest\setXvals">classes\@pest\setXvals</a>                 -  sets the 'xvals' property of the underlying smodel object.
%   <a href="matlab:help classes\@pest\setY">classes\@pest\setY</a>                     -  Set the property 'y'
%   <a href="matlab:help classes\@pest\setYforParameter">classes\@pest\setYforParameter</a>         -  Sets the according y-value for the specified parameter.
%   <a href="matlab:help classes\@pest\setYunits">classes\@pest\setYunits</a>                -  Set the property 'yunits'
%   <a href="matlab:help classes\@pest\setYunitsForParameter">classes\@pest\setYunitsForParameter</a>    -  Sets the according y-unit for the specified parameter.
%   <a href="matlab:help classes\@pest\simplifyYunits">classes\@pest\simplifyYunits</a>           -  simplifies the units of parameters in a pest
%   <a href="matlab:help classes\@pest\subset">classes\@pest\subset</a>                   -  Extract a subset of parameters from a pest.
%   <a href="matlab:help classes\@pest\table">classes\@pest\table</a>                    -  display the parameters from PEST objects in a java table.
%   <a href="matlab:help classes\@pest\tdChi2">classes\@pest\tdChi2</a>                   -  computes the chi-square for a parameter estimate.
%   <a href="matlab:help classes\@pest\toLaTeX">classes\@pest\toLaTeX</a>                  -  display the parameters from PEST objects in a LaTeX table.
%   <a href="matlab:help classes\@pest\update_struct">classes\@pest\update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@pest\viewResults">classes\@pest\viewResults</a>              -  displays the content of the pest object as an html report.
