%%%%%%%%%%%%%%%%%%%%   path: classes\@ltpda_uoh   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@ltpda_uoh\addHistory">classes\@ltpda_uoh\addHistory</a>               -  Add a history-object to the ltpda_uo object.
%   <a href="matlab:help classes\@ltpda_uoh\addHistoryWoChangingUUID">classes\@ltpda_uoh\addHistoryWoChangingUUID</a> -  Add a history-object to the ltpda_uo object.
%   <a href="matlab:help classes\@ltpda_uoh\attachToDom">classes\@ltpda_uoh\attachToDom</a>              - % Add hist
%   <a href="matlab:help classes\@ltpda_uoh\clearHistory">classes\@ltpda_uoh\clearHistory</a>             -  Clears the history of an object with history.
%   <a href="matlab:help classes\@ltpda_uoh\copy">classes\@ltpda_uoh\copy</a>                     -  copies all fields of the ltpda_uoh class to the new object.
%   <a href="matlab:help classes\@ltpda_uoh\created">classes\@ltpda_uoh\created</a>                  -  Returns a time object of the last modification.
%   <a href="matlab:help classes\@ltpda_uoh\creator">classes\@ltpda_uoh\creator</a>                  -  Extract the creator(s) from the history.
%   <a href="matlab:help classes\@ltpda_uoh\csvGenerateData">classes\@ltpda_uoh\csvGenerateData</a>          -  Default method to convert a ltpda_uoh-object into csv data.
%   <a href="matlab:help classes\@ltpda_uoh\csvexport">classes\@ltpda_uoh\csvexport</a>                -  Exports the data of an object to a csv file.
%   <a href="matlab:help classes\@ltpda_uoh\fromDom">classes\@ltpda_uoh\fromDom</a>                  - %%%%%%%%%% Call super-class
%   <a href="matlab:help classes\@ltpda_uoh\fromModel">classes\@ltpda_uoh\fromModel</a>                -  Construct an a built in model
%   <a href="matlab:help classes\@ltpda_uoh\fromRepository">classes\@ltpda_uoh\fromRepository</a>           - Retrieve a ltpda_uo from a repository
%   <a href="matlab:help classes\@ltpda_uoh\fromStruct">classes\@ltpda_uoh\fromStruct</a>               -  sets all properties which are defined in the ltpda_uoh class from the structure to the input object.
%   <a href="matlab:help classes\@ltpda_uoh\index">classes\@ltpda_uoh\index</a>                    -  index into a 'ltpda_uoh' object array or matrix. This properly captures the history.
%   <a href="matlab:help classes\@ltpda_uoh\loadobj">classes\@ltpda_uoh\loadobj</a>                  - % This is an old-type ltpda object from disk, so we don't need to
%   <a href="matlab:help classes\@ltpda_uoh\ltpda_uoh">classes\@ltpda_uoh\ltpda_uoh</a>                -  is the abstract ltpda base class for ltpda user object classes with history
%   <a href="matlab:help classes\@ltpda_uoh\plot">classes\@ltpda_uoh\plot</a>                     -  plots the user object on a figure.
%   <a href="matlab:help classes\@ltpda_uoh\prepareSinfoForSubmit">classes\@ltpda_uoh\prepareSinfoForSubmit</a>    -  This method prepend the timespan as a XML-String to the submission structure.
%   <a href="matlab:help classes\@ltpda_uoh\rebuild">classes\@ltpda_uoh\rebuild</a>                  -  rebuilds the input objects using the history.
%   <a href="matlab:help classes\@ltpda_uoh\report">classes\@ltpda_uoh\report</a>                   -  generates an HTML report about the input objects.
%   <a href="matlab:help classes\@ltpda_uoh\requirements">classes\@ltpda_uoh\requirements</a>             -  Returns a list of LTPDA extension requirements for a given object.
%   <a href="matlab:help classes\@ltpda_uoh\saveobj">classes\@ltpda_uoh\saveobj</a>                  - % MATLAB does a double pass save, firs calculating the size, then doing
%   <a href="matlab:help classes\@ltpda_uoh\setHist">classes\@ltpda_uoh\setHist</a>                  -  Set the property 'hist'
%   <a href="matlab:help classes\@ltpda_uoh\setObjectProperties">classes\@ltpda_uoh\setObjectProperties</a>      -  sets the object properties of an ltpda_uoh object.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotAxes">classes\@ltpda_uoh\setPlotAxes</a>              -  sets the 'axes' property of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotColor">classes\@ltpda_uoh\setPlotColor</a>             -  sets the color of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotFigure">classes\@ltpda_uoh\setPlotFigure</a>            -  sets the 'figure' property of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotFillmarker">classes\@ltpda_uoh\setPlotFillmarker</a>        -  defines if the plot function fill the marker or not.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotLineStyle">classes\@ltpda_uoh\setPlotLineStyle</a>         -  sets the linestyle of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotLinewidth">classes\@ltpda_uoh\setPlotLinewidth</a>         -  sets the linewidth of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotMarker">classes\@ltpda_uoh\setPlotMarker</a>            -  sets the marker of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotMarkerEdgeColor">classes\@ltpda_uoh\setPlotMarkerEdgeColor</a>   -  sets the color of a the object's marker edge.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotMarkerFaceColor">classes\@ltpda_uoh\setPlotMarkerFaceColor</a>   -  sets the color of a the object's marker face.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotMarkersize">classes\@ltpda_uoh\setPlotMarkersize</a>        -  sets the markersize of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setPlotinfo">classes\@ltpda_uoh\setPlotinfo</a>              -  sets the 'plotinfo' property of a ltpda_uoh object.
%   <a href="matlab:help classes\@ltpda_uoh\setPlottingStyle">classes\@ltpda_uoh\setPlottingStyle</a>         -  sets the style property of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setProcinfo">classes\@ltpda_uoh\setProcinfo</a>              -  sets the 'procinfo' property of a ltpda_uoh object.
%   <a href="matlab:help classes\@ltpda_uoh\setProperties">classes\@ltpda_uoh\setProperties</a>            -  set different properties of an object.
%   <a href="matlab:help classes\@ltpda_uoh\setPropertyValue">classes\@ltpda_uoh\setPropertyValue</a>         - (No help available)
%   <a href="matlab:help classes\@ltpda_uoh\setShowsErrors">classes\@ltpda_uoh\setShowsErrors</a>           -  sets the 'showErrors' property of a the object's plotinfo.
%   <a href="matlab:help classes\@ltpda_uoh\setTimespan">classes\@ltpda_uoh\setTimespan</a>              -  sets the 'timespan' property of a ltpda_uoh object.
%   <a href="matlab:help classes\@ltpda_uoh\string">classes\@ltpda_uoh\string</a>                   -  writes a command string that can be used to recreate the input object(s).
%   <a href="matlab:help classes\@ltpda_uoh\testCallerIsMethod">classes\@ltpda_uoh\testCallerIsMethod</a>       -  hidden static method which tests the 'internal' command of a LTPDA-function.
%   <a href="matlab:help classes\@ltpda_uoh\type">classes\@ltpda_uoh\type</a>                     -  converts the input objects to MATLAB functions.
%   <a href="matlab:help classes\@ltpda_uoh\viewHistory">classes\@ltpda_uoh\viewHistory</a>              -  Displays the history of an object as a dot-view or a MATLAB figure.
