%%%%%%%%%%%%%%%%%%%%   path: classes\@smodel   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes\@smodel\addAliases">classes\@smodel\addAliases</a>               -  Add the key-value pairs to the alias-names and alias-values
%   <a href="matlab:help classes\@smodel\addParameters">classes\@smodel\addParameters</a>            -  Add some parameters to the symbolic model (smodel) object
%   <a href="matlab:help classes\@smodel\assignalias">classes\@smodel\assignalias</a>              -  assign values to smodel alias
%   <a href="matlab:help classes\@smodel\attachToDom">classes\@smodel\attachToDom</a>              - % Create empty smodel node with the attribute 'shape'
%   <a href="matlab:help classes\@smodel\char">classes\@smodel\char</a>                     -  convert a smodel object into a string.
%   <a href="matlab:help classes\@smodel\clearAliases">classes\@smodel\clearAliases</a>             -  Clear the aliases.
%   <a href="matlab:help classes\@smodel\conj">classes\@smodel\conj</a>                     -  gives the complex conjugate of the input smodels
%   <a href="matlab:help classes\@smodel\convol_integral">classes\@smodel\convol_integral</a>          -  implements the convolution integral for smodel objects.
%   <a href="matlab:help classes\@smodel\copy">classes\@smodel\copy</a>                     -  makes a (deep) copy of the input smodel objects.
%   <a href="matlab:help classes\@smodel\det">classes\@smodel\det</a>                      -  evaluates the determinant of smodel objects.
%   <a href="matlab:help classes\@smodel\diff">classes\@smodel\diff</a>                     -  implements differentiation operator for smodel objects.
%   <a href="matlab:help classes\@smodel\disp">classes\@smodel\disp</a>                     -  overloads display functionality for smodel objects.
%   <a href="matlab:help classes\@smodel\double">classes\@smodel\double</a>                   -  Returns the numeric result of the model.
%   <a href="matlab:help classes\@smodel\elementOp">classes\@smodel\elementOp</a>                -  applies the given operator to the input smodels.
%   <a href="matlab:help classes\@smodel\eval">classes\@smodel\eval</a>                     -  evaluates the symbolic model and returns an AO containing the numeric data.
%   <a href="matlab:help classes\@smodel\fitfunc">classes\@smodel\fitfunc</a>                  -  Returns a function handle which sets the 'values' and 'xvals' to a ltpda model.
%   <a href="matlab:help classes\@smodel\fourier">classes\@smodel\fourier</a>                  -  implements continuous f-domain Fourier transform for smodel objects.
%   <a href="matlab:help classes\@smodel\fromDatafile">classes\@smodel\fromDatafile</a>             -  Construct smodel object from filename AND parameter list
%   <a href="matlab:help classes\@smodel\fromDom">classes\@smodel\fromDom</a>                  - % Get shape
%   <a href="matlab:help classes\@smodel\fromExpression">classes\@smodel\fromExpression</a>           - (No help available)
%   <a href="matlab:help classes\@smodel\fromStruct">classes\@smodel\fromStruct</a>               -  creates from a structure a SMODEL object.
%   <a href="matlab:help classes\@smodel\generateConstructorPlist">classes\@smodel\generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help classes\@smodel\hessian">classes\@smodel\hessian</a>                  -  compute the hessian matrix for a symbolic model.
%   <a href="matlab:help classes\@smodel\ifourier">classes\@smodel\ifourier</a>                 -  implements continuous f-domain inverse Fourier transform for smodel objects.
%   <a href="matlab:help classes\@smodel\ilaplace">classes\@smodel\ilaplace</a>                 -  implements continuous s-domain inverse Laplace transform for smodel objects.
%   <a href="matlab:help classes\@smodel\inv">classes\@smodel\inv</a>                      -  evaluates the inverse of smodel objects.
%   <a href="matlab:help classes\@smodel\iztrans">classes\@smodel\iztrans</a>                  -  implements continuous z-domain inverse Z-transform for smodel objects.
%   <a href="matlab:help classes\@smodel\laplace">classes\@smodel\laplace</a>                  -  implements continuous s-domain Laplace transform for smodel objects.
%   <a href="matlab:help classes\@smodel\linearize">classes\@smodel\linearize</a>                -  output the derivatives of the model relative to the parameters.
%   <a href="matlab:help classes\@smodel\loadobj">classes\@smodel\loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help classes\@smodel\mergeFields">classes\@smodel\mergeFields</a>              -  merges properties (name/values) of smodels
%   <a href="matlab:help classes\@smodel\minus">classes\@smodel\minus</a>                    -  implements subtraction operator for smodel objects.
%   <a href="matlab:help classes\@smodel\mrdivide">classes\@smodel\mrdivide</a>                 -  implements mrdivide operator for smodel objects.
%   <a href="matlab:help classes\@smodel\mtimes">classes\@smodel\mtimes</a>                   -  implements mtimes operator for smodel objects.
%   <a href="matlab:help classes\@smodel\op">classes\@smodel\op</a>                       -  Add a operation around the model expression
%   <a href="matlab:help classes\@smodel\plus">classes\@smodel\plus</a>                     -  implements addition operator for smodel objects.
%   <a href="matlab:help classes\@smodel\rdivide">classes\@smodel\rdivide</a>                  -  implements division operator for smodel objects.
%   <a href="matlab:help classes\@smodel\setAliasNames">classes\@smodel\setAliasNames</a>            -  Set the property 'aliasNames'
%   <a href="matlab:help classes\@smodel\setAliasValues">classes\@smodel\setAliasValues</a>           -  Set the property 'aliasValues'
%   <a href="matlab:help classes\@smodel\setAliases">classes\@smodel\setAliases</a>               -  Set the key-value pairs to the alias-names and alias-values
%   <a href="matlab:help classes\@smodel\setExpr">classes\@smodel\setExpr</a>                  -  sets the 'expr' property of the smodel object.
%   <a href="matlab:help classes\@smodel\setParameters">classes\@smodel\setParameters</a>            -  Set some parameters to the symbolic model (smodel) object
%   <a href="matlab:help classes\@smodel\setParams">classes\@smodel\setParams</a>                -  Set the property 'params' AND 'values'
%   <a href="matlab:help classes\@smodel\setTrans">classes\@smodel\setTrans</a>                 -  sets the 'trans' property of the smodel object.
%   <a href="matlab:help classes\@smodel\setValues">classes\@smodel\setValues</a>                -  Set the property 'values'
%   <a href="matlab:help classes\@smodel\setXunits">classes\@smodel\setXunits</a>                -  sets the 'xunits' property of the smodel object.
%   <a href="matlab:help classes\@smodel\setXvals">classes\@smodel\setXvals</a>                 -  sets the 'xvals' property of the smodel object.
%   <a href="matlab:help classes\@smodel\setXvar">classes\@smodel\setXvar</a>                  -  sets the 'xvar' property of the smodel object.
%   <a href="matlab:help classes\@smodel\setYunits">classes\@smodel\setYunits</a>                -  sets the 'yunits' property of the smodel object.
%   <a href="matlab:help classes\@smodel\simplify">classes\@smodel\simplify</a>                 -  implements simplify operator for smodel objects.
%   <a href="matlab:help classes\@smodel\simplifyUnits">classes\@smodel\simplifyUnits</a>            -  simplify the x and/or y units of the model.
%   <a href="matlab:help classes\@smodel\smodel">classes\@smodel\smodel</a>                   -  constructor for smodel class.
%   <a href="matlab:help classes\@smodel\sop">classes\@smodel\sop</a>                      -  apply a symbolic operation to the expression.
%   <a href="matlab:help classes\@smodel\subs">classes\@smodel\subs</a>                     -  substitutes symbolic parameters with the given values.
%   <a href="matlab:help classes\@smodel\sum">classes\@smodel\sum</a>                      -  adds all the elements of smodel objects arrays.
%   <a href="matlab:help classes\@smodel\times">classes\@smodel\times</a>                    -  implements multiplication operator for smodel objects.
%   <a href="matlab:help classes\@smodel\update_struct">classes\@smodel\update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help classes\@smodel\ztrans">classes\@smodel\ztrans</a>                   -  implements continuous z-domain Z-transform for smodel objects.
